#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Hand-derived, production-independent oracle for SPP boot authority v3.

The literals and validators in this file are intentionally maintained apart
from the v3 implementation.  They check the finite authority vocabulary, not
an implementation round trip.
"""

from __future__ import annotations

import ast
import hashlib
import struct
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from conf_proc_spp_reasons_v3 import (
    CP_BOOT_V3_CONTROL,
    CP_BOOT_V3_DEV_TREE,
    CP_BOOT_V3_FAILURE_PROTOCOL,
    CP_BOOT_V3_LATCH,
    CP_BOOT_V3_LAUNCH_SUPERVISION,
    CP_BOOT_V3_MODULE_AUTHORITY,
    CP_BOOT_V3_NETWORK_POLICY,
    CP_BOOT_V3_PCR,
    CP_BOOT_V3_RESOURCE_REDUCER,
)


DOMAIN_V3 = b"sol-spp-appliance-manifest-v3\0"
MEASUREMENT_VECTOR_V3 = (
    b"root-lock-v3",
    b"runtime-closure-v3",
    b"verity-rules-v3",
    b"tcb-identity-v3",
    b"builder-source-v3",
    b"policy-v3",
    b"accepted-manifest-v3",
    b"kernel-feature-contract-v3",
    b"trusted-certificate-bundle-v3",
    b"boot-contract-v3",
    b"module-plan-v3",
    b"gpt-layout-rules-v3",
    b"literal-v3-observation-shape",
)
MEASUREMENT_VECTOR_SHA256_V3 = "bb7ed0482c4ba1cb8cfb63c124eb4f0f5efc89af46a35852f52e5076b4c38767"
PREDICTED_PCR15_SHA256_V3 = "87661084bac241b4f56683a52c901888d0688ee5796ad7892cb540cfee4302ba"

EARLY_KERNEL_RELEASE_V3 = "6.8.0-1058-azure-fde"
EARLY_KERNEL_CONFIG_SHA256_V3 = "1ce93dd4569a7607db57f2b3321d38d0e0122fe29efa430374c3717ccbde68b9"
EARLY_MODULE_SIGNER_V3 = "Build time autogenerated kernel key"
EARLY_MODULE_KEY_ID_V3 = "4C:F4:E0:34:2A:28:95:F1:5C:29:6C:20:CC:25:FC:B8:61:8D:B5:24"
EARLY_MODULE_RELEASE_ROOT_V3 = "/lib/modules/6.8.0-1058-azure-fde/"
EARLY_MODULE_ROWS_V3 = (
    ("kernel/drivers/md/dm-bufio.ko", "318df552f245da0e3bce5c047443f349d3771f044bfd9573ebe486a9056d107c"),
    ("kernel/drivers/md/dm-verity.ko", "31f7c5f1832ed81d4fa9290396d559b6e82d68eadb2df8b157fb71968431b6dc"),
    ("kernel/lib/libcrc32c.ko", "de152f89a11624f60b5c2ab74ff2bda86a1a8ecc7d110b37147e61abd5ab3c63"),
    ("kernel/net/netfilter/nfnetlink.ko", "b5eea11e088608fd57efaa8baf6059df9d4b0182df091bd2af7f686530cc69d3"),
    ("kernel/net/netfilter/nf_tables.ko", "2ea6941010d02f6c548fc259be178289a47698859ac9e6bcbbb30426bfd16589"),
)
EARLY_MODULE_BUILT_INS_V3 = ("crc32c_intel", "crc32c_generic")
KERNEL_CONFIG_ROWS_V3 = (
    ("CONFIG_DEVTMPFS", "y"),
    ("CONFIG_BLK_DEV_NVME", "y"),
    ("CONFIG_BLK_DEV_DM", "y"),
    ("CONFIG_SQUASHFS", "y"),
    ("CONFIG_TCG_TPM", "y"),
    ("CONFIG_TCG_CRB", "y"),
    ("CONFIG_NETFILTER", "y"),
    ("CONFIG_DM_VERITY", "m"),
    ("CONFIG_NF_TABLES", "m"),
)

CONTROL_NAMES_V3 = (
    "modules",
    "kexec",
    "sysrq",
    "unprivileged_bpf",
    "userfaultfd",
    "kernel_debug",
    "recovery_operator_ingress",
    "writable_roots",
    "tpm_closure",
    "persistence",
)
KERNEL_READBACK_IDENTITY_V3 = "stage2-pid1:kernel-namespace"
MOUNT_READBACK_IDENTITY_V3 = "stage2-pid1:mount-namespace"
TPM_READBACK_IDENTITY_V3 = "sealed-attestation-broker:tpmrm0"
RECOVERY_ABSENT_V3 = (
    "init=",
    "rd.break",
    "systemd.unit=",
    "systemd.debug_shell",
    "rescue",
    "emergency",
    "recovery",
    "getty",
    "serial_reader",
    "ssh",
    "azure_agent",
    "run_command_or_extension_agent",
    "cloud_init",
    "container_socket",
    "interactive_process_or_listener",
)
WRITABLE_ROOT_REQUIREMENTS_V3 = (
    "root_mapping_read_only",
    "model_mapping_read_only",
    "ordinary_tmpfs:nosuid,nodev,noexec",
    "at_most_one_declared_jit_tmpfs:nosuid,nodev",
    "no_other_writable_executable_disk_backed_or_bind_backed_mount",
)
TPM_CLOSURE_REQUIREMENTS_V3 = (
    "one_attestation_broker_tpmrm0_after_extend",
    "quote_and_pcr_read_only",
    "root_owned_unix_socket",
    "pid1_gateway_collector_model_no_tpm_capability",
)
PERSISTENCE_REQUIREMENTS_V3 = (
    "proc_swaps_empty",
    "kdump_absent",
    "coredumps_disabled",
    "persistent_journaling_absent",
    "no_writable_block_device_mounted",
    "writable_roots_declared_reboot_ephemeral_tmpfs",
)

DEV_DIRECTORIES_V3 = (("/dev", 0o755, 0, 0), ("/dev/nvidia-caps", 0o755, 0, 0))
SEALED_BROKER_UID_V3 = "sealed-attestation-broker-uid"
SEALED_BROKER_GID_V3 = "sealed-attestation-broker-gid"
def _dev_rows_v3():
    yield ("/dev/console", "char", "literal", 5, 1, 0o600, 0, 0)
    yield ("/dev/null", "char", "literal", 1, 3, 0o666, 0, 0)
    yield ("/dev/zero", "char", "literal", 1, 5, 0o666, 0, 0)
    yield ("/dev/full", "char", "literal", 1, 7, 0o666, 0, 0)
    yield ("/dev/random", "char", "literal", 1, 8, 0o666, 0, 0)
    yield ("/dev/urandom", "char", "literal", 1, 9, 0o666, 0, 0)
    yield ("/dev/tpmrm0", "char", "registered", "tpm_rm", 65536, 0o660, SEALED_BROKER_UID_V3, SEALED_BROKER_GID_V3)
    yield ("/dev/nvidia0", "char", "registered", "nvidia_gpu", 0, 0o666, 0, 0)
    yield ("/dev/nvidiactl", "char", "registered", "nvidia_gpu", 255, 0o666, 0, 0)
    yield ("/dev/nvidia-uvm", "char", "registered", "nvidia_uvm", 0, 0o666, 0, 0)
    yield ("/dev/nvidia-uvm-tools", "char", "registered", "nvidia_uvm", 1, 0o666, 0, 0)
    yield ("/dev/nvidia-caps/nvidia-cap1", "char", "registered", "nvidia_caps", 1, 0o400, 0, 0)
    yield ("/dev/nvidia-caps/nvidia-cap2", "char", "registered", "nvidia_caps", 2, 0o400, 0, 0)


DEV_ROWS_V3 = tuple(_dev_rows_v3())
REGISTERED_MAJORS_V3 = {"tpm_rm": 240, "nvidia_gpu": 195, "nvidia_uvm": 511, "nvidia_caps": 508}

LAUNCH_ROLES_V3 = (
    ("attestation-broker", 1, "long_lived", "no_network", "one_root_owned_local_socket", "never"),
    ("inference", 1, "long_lived", "loopback:127.0.0.1:8000", "one_listener", "never"),
    ("asr", 1, "long_lived", "loopback:127.0.0.1:8100", "one_listener", "never"),
    ("gateway", 1, "long_lived", "ra_tls_only", "no_listener_pid1_admitted_connected_fds", "never"),
    ("collector", (0, 1), "transient", "no_network_listener", "pid1_spawn_reap_one_bounded_request_response", "never"),
)
RESOURCE_ACTIONS_V3 = (
    "session_acquire",
    "collector_acquire",
    "collector_finish",
    "collector_abort",
    "request_acquire",
    "work_begin",
    "work_finish",
    "request_release",
    "session_release",
    "global_revoke",
)
RESOURCE_CAPACITIES_V3 = {
    "listen_backlog": 8,
    "somaxconn_minimum": 8,
    "max_live_sessions": 4,
    "collector_operation_permits": 1,
    "collector_operation_bound_seconds": 180,
    "collector_output_capacity_bytes": 8388608,
    "route_work_permits_total": 2,
    "stream_buffer_bytes": 2097152,
    "aggregate_buffer_bytes": 4194304,
    "request_head_capacity_bytes": 32768,
    "relay_copy_chunk_bytes": 65536,
}

WIRE_TYPES_V3 = (
    (1, "SESSION_FD"), (2, "COLLECTOR_REQUEST"), (3, "COLLECTOR_RESPONSE"),
    (4, "COLLECTOR_ACK_VALID"), (5, "COLLECTOR_ACK_INVALID"), (6, "COLLECTOR_CANCEL"),
    (7, "REQUEST_ACQUIRE"), (8, "REQUEST_ADMIT"), (9, "REQUEST_REJECT"),
    (10, "WORK_BEGIN"), (11, "WORK_BEGUN"), (12, "WORK_FINISH"),
    (13, "WORK_FINISHED"), (14, "REQUEST_RELEASE"), (15, "REQUEST_RELEASED"),
    (16, "SESSION_RELEASE"), (17, "SESSION_RELEASED"), (18, "PRE_REQUEST_REJECTED"),
    (19, "GLOBAL_FAULT"), (20, "CHUNK_ACK"), (21, "SESSION_FD_ACK"),
    (22, "GATEWAY_READINESS_PROBE"), (23, "GATEWAY_READINESS_RESULT"),
)
HEADER_MAGIC_V3 = b"SPPIPC3\0"
HEADER_FORMAT_V3 = ">8sHHHHIIIIQ32s"
HEADER_SIZE_V3 = 72
HEADER_VERSION_V3 = 3
START_FLAG_V3 = 1
END_FLAG_V3 = 2
HAS_FD_FLAG_V3 = 4
MAX_CHUNK_PAYLOAD_BYTES_V3 = 16384
MAX_COLLECTOR_RESPONSE_BYTES_V3 = 44 + 8388608

def _serving_session_rows_v3():
    yield "request_started", "session_readback"
    yield "credential_observed", "handle_and_bearer_sha256"
    yield "entitlement_dns_query", "session_readback"
    yield "entitlement_dns_result", "token_ipv4_ttl"
    yield "entitlement_tls_connect", "token_ipv4_dns_age"
    yield "entitlement_tls_verified", "accepted_readback"
    yield "entitlement_authorize_request", "session_readback"
    yield "entitlement_authorized", "accepted_or_denied_readback"
    yield "upstream_open", "role_address_socket_readback"
    yield "upstream_opened", "completion_readback"
    yield "reject_413", "status_write_and_close_requested"
    yield "drain_exact", "drained_count_and_close_requested"


SERVING_SESSION_ROWS_V3 = tuple(_serving_session_rows_v3())
SERVING_DEADLINES_V3 = {
    "credential": 5,
    "dns": 5,
    "upstream": 5,
    "close": 5,
    "tls": 10,
    "authorization": 10,
    "drain": 15,
}
AUDIO_OVERSIZE_LIMIT_V3 = 11534336
AUDIO_FORCED_CLOSE_LIMIT_V3 = 67108864

FAILURE_TOKENS_V3 = (
    "authority", "binding", "pid1", "adapter", "root_transition", "runtime_authority", "serving_integrity",
)
FAILURE_LATE_CODES_V3 = ("network_close", "poweroff_returned")
FAILURE_STAGES_V3 = ("diagnostic", "close_serving_network", "poweroff_requested", "fail_stop")
FAILURE_TRIGGER_MAPPING_V3 = {
    "before_schema_selection": "authority",
    "cross_document_conjunction": "binding",
    "pid1_setup": "pid1",
    "adapter_first_effect": "adapter",
    "bootstrap_through_last_pre_root_disk": "runtime_authority",
    "first_root_map_through_c4_admission": "root_transition",
    "first_post_c4_through_pre_launch": "runtime_authority",
    "first_process_launch": "serving_integrity",
    "post_activation_identity_drift": "serving_integrity",
}

REASON_CODES_V3 = frozenset({
    "CP_BOOT_V3_PCR",
    "CP_BOOT_V3_LATCH",
    "CP_BOOT_V3_MODULE_AUTHORITY",
    "CP_BOOT_V3_NETWORK_POLICY",
    "CP_BOOT_V3_CONTROL",
    "CP_BOOT_V3_DEV_TREE",
    "CP_BOOT_V3_LAUNCH_SUPERVISION",
    "CP_BOOT_V3_RESOURCE_REDUCER",
    "CP_BOOT_V3_FAILURE_PROTOCOL",
})


def _frame(value: bytes) -> bytes:
    return len(value).to_bytes(8, "big") + value


def _measurement(*values: bytes) -> bytes:
    if len(values) != 13 or any(type(value) is not bytes for value in values):
        raise ValueError(CP_BOOT_V3_PCR)
    return hashlib.sha256(DOMAIN_V3 + b"".join(_frame(value) for value in values)).digest()


def _predicted_pcr(measurement: bytes) -> bytes:
    if type(measurement) is not bytes or len(measurement) != 32:
        raise ValueError(CP_BOOT_V3_PCR)
    return hashlib.sha256(b"\0" * 32 + measurement).digest()


def _accept_early_modules(
    rows: object,
    *,
    release: object,
    config_sha256: object,
    signer: object,
    key_id: object,
    release_root: object,
    built_ins: object,
    signed: object,
) -> None:
    if (
        rows != EARLY_MODULE_ROWS_V3
        or release != EARLY_KERNEL_RELEASE_V3
        or config_sha256 != EARLY_KERNEL_CONFIG_SHA256_V3
        or signer != EARLY_MODULE_SIGNER_V3
        or key_id != EARLY_MODULE_KEY_ID_V3
        or release_root != EARLY_MODULE_RELEASE_ROOT_V3
        or built_ins != EARLY_MODULE_BUILT_INS_V3
        or signed is not True
    ):
        raise ValueError(CP_BOOT_V3_MODULE_AUTHORITY)


def _accept_kernel_config(rows: object, *, release: object, config_sha256: object) -> None:
    if rows != KERNEL_CONFIG_ROWS_V3 or release != EARLY_KERNEL_RELEASE_V3 or config_sha256 != EARLY_KERNEL_CONFIG_SHA256_V3:
        raise ValueError(CP_BOOT_V3_MODULE_AUTHORITY)


def _accept_prefirewall_network(
    *,
    cmdline: object,
    initial_nics: object,
    final_nics: object,
    inet_socket_count: object,
    packet_socket_count: object,
    monitor_sockets: object,
    enobufs: object,
    rxq_ovfl: object,
    ack_sequence_matches: object,
    dump_generation_contiguous: object,
    monitor_close_reopen: object,
    uncorrelated_event: object,
    final_queue: object,
) -> None:
    if type(cmdline) is not tuple or sum(token == "ip=off" for token in cmdline) != 1:
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    if any(token == "rd.neednet" or token.startswith("BOOTIF=") or token.startswith("net.ifnames=") or token.startswith("biosdevname=") for token in cmdline):
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    if type(initial_nics) is not tuple or not initial_nics:
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    for nic in initial_nics:
        if type(nic) is not tuple or len(nic) != 4 or type(nic[0]) is not str or nic[0] == "lo" or nic[1:] != (False, False, False):
            raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    if final_nics != initial_nics or inet_socket_count != 0 or packet_socket_count != 0:
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    if monitor_sockets != (("AF_NETLINK", "NETLINK_ROUTE", "bound"),):
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)
    if (
        enobufs is not False
        or rxq_ovfl is not False
        or ack_sequence_matches is not True
        or dump_generation_contiguous is not True
        or monitor_close_reopen is not False
        or uncorrelated_event is not False
        or final_queue != ()
    ):
        raise ValueError(CP_BOOT_V3_NETWORK_POLICY)


def _control_fixture() -> dict[str, object]:
    return {
        "modules": (0, 1, KERNEL_READBACK_IDENTITY_V3, True),
        "kexec": (0, 1, "integrity", True, KERNEL_READBACK_IDENTITY_V3),
        "sysrq": (511, 0, KERNEL_READBACK_IDENTITY_V3),
        "unprivileged_bpf": (2, 1, KERNEL_READBACK_IDENTITY_V3),
        "userfaultfd": (1, 0, KERNEL_READBACK_IDENTITY_V3),
        "kernel_debug": ((2, 2), (1, 1), (4, 4), (3, 3), False, False, KERNEL_READBACK_IDENTITY_V3),
        "recovery_operator_ingress": RECOVERY_ABSENT_V3,
        "writable_roots": (WRITABLE_ROOT_REQUIREMENTS_V3, MOUNT_READBACK_IDENTITY_V3),
        "tpm_closure": (TPM_CLOSURE_REQUIREMENTS_V3, TPM_READBACK_IDENTITY_V3),
        "persistence": (PERSISTENCE_REQUIREMENTS_V3, MOUNT_READBACK_IDENTITY_V3),
    }


def _is_exact_int(value: object) -> bool:
    return type(value) is int


def _accept_controls(controls: object) -> None:
    if type(controls) is not dict or tuple(controls) != CONTROL_NAMES_V3:
        raise ValueError(CP_BOOT_V3_CONTROL)
    modules = controls["modules"]
    if modules != (0, 1, KERNEL_READBACK_IDENTITY_V3, True):
        raise ValueError(CP_BOOT_V3_CONTROL)
    kexec = controls["kexec"]
    if type(kexec) is not tuple or len(kexec) != 5 or kexec[0] not in (0, 1) or kexec[1] != 1 or kexec[2] not in ("integrity", "confidentiality") or kexec[3] is not True or kexec[4] != KERNEL_READBACK_IDENTITY_V3:
        raise ValueError(CP_BOOT_V3_CONTROL)
    sysrq = controls["sysrq"]
    if type(sysrq) is not tuple or len(sysrq) != 3 or not _is_exact_int(sysrq[0]) or not 0 <= sysrq[0] <= 511 or sysrq[1:] != (0, KERNEL_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)
    unprivileged_bpf = controls["unprivileged_bpf"]
    if type(unprivileged_bpf) is not tuple or len(unprivileged_bpf) != 3 or unprivileged_bpf[0] not in (0, 1, 2) or unprivileged_bpf[1:] != (1, KERNEL_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)
    userfaultfd = controls["userfaultfd"]
    if type(userfaultfd) is not tuple or len(userfaultfd) != 3 or userfaultfd[0] not in (0, 1) or userfaultfd[1:] != (0, KERNEL_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)
    kernel_debug = controls["kernel_debug"]
    if type(kernel_debug) is not tuple or len(kernel_debug) != 7:
        raise ValueError(CP_BOOT_V3_CONTROL)
    kptr, dmesg, perf, ptrace, debugfs_present, kcore_accessible, debug_identity = kernel_debug
    if (
        type(kptr) is not tuple or kptr[0] not in (0, 1, 2) or kptr[1] != 2
        or type(dmesg) is not tuple or dmesg[0] not in (0, 1) or dmesg[1] != 1
        or type(perf) is not tuple or perf[0] not in (-1, 0, 1, 2, 3, 4) or perf[1] != max(perf[0], 3) or perf[1] not in (3, 4)
        or type(ptrace) is not tuple or ptrace[0] not in (0, 1, 2, 3) or ptrace[1] != 3
        or debugfs_present is not False or kcore_accessible is not False or debug_identity != KERNEL_READBACK_IDENTITY_V3
    ):
        raise ValueError(CP_BOOT_V3_CONTROL)
    if controls["recovery_operator_ingress"] != RECOVERY_ABSENT_V3:
        raise ValueError(CP_BOOT_V3_CONTROL)
    writable_roots = controls["writable_roots"]
    if writable_roots != (WRITABLE_ROOT_REQUIREMENTS_V3, MOUNT_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)
    tpm_closure = controls["tpm_closure"]
    if tpm_closure != (TPM_CLOSURE_REQUIREMENTS_V3, TPM_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)
    persistence = controls["persistence"]
    if persistence != (PERSISTENCE_REQUIREMENTS_V3, MOUNT_READBACK_IDENTITY_V3):
        raise ValueError(CP_BOOT_V3_CONTROL)


def _resolved_dev_rows(registrations: dict[str, int]) -> tuple[tuple[object, ...], ...]:
    rows = []
    for path, kind, major_kind, major_or_key, minor, mode, uid, gid in DEV_ROWS_V3:
        major = major_or_key if major_kind == "literal" else registrations[major_or_key]
        rows.append((path, kind, major, minor, mode, uid, gid))
    return tuple(rows)


def _forbidden_dev_path(path: str) -> bool:
    allowed = {row[0] for row in DEV_ROWS_V3} | {row[0] for row in DEV_DIRECTORIES_V3}
    return (
        path in {"/dev/tpm0", "/dev/mapper/control", "/dev/kmsg", "/dev/mem", "/dev/kmem", "/dev/port"}
        or path.startswith("/dev/dm-")
        or path.startswith("/dev/tty")
        or path == "/dev/ptmx"
        or path.startswith("/dev/pts/")
        or path.startswith("/dev/dri/")
        or (path.startswith("/dev/nvidia") and path not in allowed)
        or path.startswith("/dev/block/")
    )


def _accept_dev_tree(
    directories: object,
    nodes: object,
    registrations: object,
    other_nodes: object,
) -> None:
    if directories != DEV_DIRECTORIES_V3 or type(registrations) is not dict or set(registrations) != {"tpm_rm", "nvidia_gpu", "nvidia_uvm", "nvidia_caps"}:
        raise ValueError(CP_BOOT_V3_DEV_TREE)
    if any(type(value) is not int for value in registrations.values()):
        raise ValueError(CP_BOOT_V3_DEV_TREE)
    if len(set(registrations.values())) != 4 or set(registrations.values()) & {1, 5}:
        raise ValueError(CP_BOOT_V3_DEV_TREE)
    if nodes != _resolved_dev_rows(registrations):
        raise ValueError(CP_BOOT_V3_DEV_TREE)
    if type(other_nodes) is not tuple:
        raise ValueError(CP_BOOT_V3_DEV_TREE)
    for path, kind in other_nodes:
        if kind in {"symlink", "regular", "socket", "fifo", "submount"} or _forbidden_dev_path(path) or path not in {row[0] for row in DEV_ROWS_V3}:
            raise ValueError(CP_BOOT_V3_DEV_TREE)
    if other_nodes:
        raise ValueError(CP_BOOT_V3_DEV_TREE)


def _launch_fixture() -> dict[str, tuple[object, ...]]:
    return {row[0]: row[1:] for row in LAUNCH_ROLES_V3}


def _accept_launch_inventory(roles: object) -> None:
    if type(roles) is not dict or tuple(roles) != tuple(row[0] for row in LAUNCH_ROLES_V3):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)
    if roles["attestation-broker"] != (1, "long_lived", "no_network", "one_root_owned_local_socket", "never"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)
    if roles["inference"] != (1, "long_lived", "loopback:127.0.0.1:8000", "one_listener", "never"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)
    if roles["asr"] != (1, "long_lived", "loopback:127.0.0.1:8100", "one_listener", "never"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)
    if roles["gateway"] != (1, "long_lived", "ra_tls_only", "no_listener_pid1_admitted_connected_fds", "never"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)
    if roles["collector"] != ((0, 1), "transient", "no_network_listener", "pid1_spawn_reap_one_bounded_request_response", "never"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)


def _accept_long_lived_exit(role: object, actions: object) -> None:
    if role not in {"attestation-broker", "inference", "asr", "gateway"} or actions != ("ingress_close", "terminal_failure"):
        raise ValueError(CP_BOOT_V3_LAUNCH_SUPERVISION)


def _accept_resource_inventory(actions: object, capacities: object) -> None:
    if actions != RESOURCE_ACTIONS_V3 or capacities != RESOURCE_CAPACITIES_V3:
        raise ValueError(CP_BOOT_V3_RESOURCE_REDUCER)


def _two_route_permits(capacities: dict[str, int], routes: tuple[str, ...]) -> tuple[bytes, ...]:
    if routes != ("inference", "asr") or capacities["route_work_permits_total"] != 2:
        raise ValueError(CP_BOOT_V3_RESOURCE_REDUCER)
    return tuple(bytes([index + 1]) * capacities["stream_buffer_bytes"] for index in range(2))


def _session_decision(capacities: dict[str, int], live_sessions: int) -> str:
    return "session_saturated" if live_sessions >= capacities["max_live_sessions"] else "session_admitted"


def _request_decision(active_routes: tuple[str, ...], route: str) -> str:
    return "route_work_saturated" if route in active_routes else "request_admitted"


def _accept_wire_type(value: object) -> None:
    if type(value) is not int or value not in {number for number, _name in WIRE_TYPES_V3}:
        raise ValueError("wire-type")


def _encode_header(message_type: int, flags: int, sequence: int, payload_length: int, token: bytes) -> bytes:
    _accept_wire_type(message_type)
    if flags not in range(8) or type(sequence) is not int or type(payload_length) is not int or not 0 <= payload_length <= MAX_CHUNK_PAYLOAD_BYTES_V3 or type(token) is not bytes or len(token) != 32:
        raise ValueError("wire-header")
    return struct.pack(HEADER_FORMAT_V3, HEADER_MAGIC_V3, HEADER_VERSION_V3, message_type, flags, 0, sequence, 0, 1, payload_length, payload_length, token)


def _decode_header(value: bytes) -> tuple[object, ...]:
    if type(value) is not bytes or len(value) != HEADER_SIZE_V3:
        raise ValueError("wire-header")
    fields = struct.unpack(HEADER_FORMAT_V3, value)
    magic, version, message_type, flags, reserved, _sequence, _index, _count, chunk_length, total_length, token = fields
    if magic != HEADER_MAGIC_V3 or version != HEADER_VERSION_V3 or reserved != 0 or flags not in range(8) or chunk_length > MAX_CHUNK_PAYLOAD_BYTES_V3 or total_length != chunk_length or len(token) != 32:
        raise ValueError("wire-header")
    _accept_wire_type(message_type)
    return fields


def _accept_serving_session_rows(rows: object, deadlines: object) -> None:
    if rows != SERVING_SESSION_ROWS_V3 or deadlines != SERVING_DEADLINES_V3:
        raise ValueError("serving-session")


def _audio_branch(length: object) -> str:
    if type(length) is not int or length < 0:
        raise ValueError("audio-length")
    if length <= AUDIO_OVERSIZE_LIMIT_V3:
        return "pass"
    if length <= AUDIO_FORCED_CLOSE_LIMIT_V3:
        return "413_drain"
    return "413_hard_close"


def _accept_failure_mapping(mapping: object) -> None:
    if type(mapping) is not dict or mapping != FAILURE_TRIGGER_MAPPING_V3:
        raise ValueError(CP_BOOT_V3_FAILURE_PROTOCOL)
    if set(mapping.values()) != set(FAILURE_TOKENS_V3):
        raise ValueError(CP_BOOT_V3_FAILURE_PROTOCOL)
    if FAILURE_LATE_CODES_V3 != ("network_close", "poweroff_returned") or FAILURE_STAGES_V3 != ("diagnostic", "close_serving_network", "poweroff_requested", "fail_stop"):
        raise ValueError(CP_BOOT_V3_FAILURE_PROTOCOL)


class BootV3RawOracleTests(unittest.TestCase):
    def test_a_pcr15_domain_framing_and_known_vector(self) -> None:
        self.assertEqual(DOMAIN_V3, b"sol-spp-appliance-manifest-v3\0")
        self.assertEqual(_measurement(*MEASUREMENT_VECTOR_V3).hex(), MEASUREMENT_VECTOR_SHA256_V3)
        self.assertEqual(_predicted_pcr(_measurement(*MEASUREMENT_VECTOR_V3)).hex(), PREDICTED_PCR15_SHA256_V3)
        hand_material = DOMAIN_V3 + b"".join(len(value).to_bytes(8, "big") + value for value in MEASUREMENT_VECTOR_V3)
        self.assertEqual(hashlib.sha256(hand_material).hexdigest(), MEASUREMENT_VECTOR_SHA256_V3)
        self.assertNotEqual(hashlib.sha256(DOMAIN_V3 + b"".join(_frame(value) for value in MEASUREMENT_VECTOR_V3[:-1])).digest(), _measurement(*MEASUREMENT_VECTOR_V3))
        reordered = (*MEASUREMENT_VECTOR_V3[:4], MEASUREMENT_VECTOR_V3[5], MEASUREMENT_VECTOR_V3[4], *MEASUREMENT_VECTOR_V3[6:])
        self.assertNotEqual(_measurement(*reordered), _measurement(*MEASUREMENT_VECTOR_V3))
        truncated_prefix = DOMAIN_V3 + len(MEASUREMENT_VECTOR_V3[0]).to_bytes(7, "big") + MEASUREMENT_VECTOR_V3[0] + b"".join(_frame(value) for value in MEASUREMENT_VECTOR_V3[1:])
        self.assertNotEqual(hashlib.sha256(truncated_prefix).digest(), _measurement(*MEASUREMENT_VECTOR_V3))
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_PCR):
            _measurement(*MEASUREMENT_VECTOR_V3[:-1])

    def test_b_early_modules_and_kernel_config_are_closed(self) -> None:
        arguments = dict(release=EARLY_KERNEL_RELEASE_V3, config_sha256=EARLY_KERNEL_CONFIG_SHA256_V3, signer=EARLY_MODULE_SIGNER_V3, key_id=EARLY_MODULE_KEY_ID_V3, release_root=EARLY_MODULE_RELEASE_ROOT_V3, built_ins=EARLY_MODULE_BUILT_INS_V3, signed=True)
        _accept_early_modules(EARLY_MODULE_ROWS_V3, **arguments)
        for changed in (EARLY_MODULE_ROWS_V3[:-1], EARLY_MODULE_ROWS_V3 + (EARLY_MODULE_ROWS_V3[0],), tuple(reversed(EARLY_MODULE_ROWS_V3)), ((EARLY_MODULE_ROWS_V3[0][0], "0" * 64), *EARLY_MODULE_ROWS_V3[1:])):
            with self.subTest(module_rows=changed), self.assertRaisesRegex(ValueError, CP_BOOT_V3_MODULE_AUTHORITY):
                _accept_early_modules(changed, **arguments)
        for keyword, value in (("signer", "foreign signer"), ("signed", False), ("release", "6.8.0-1058-azure")):
            changed = dict(arguments)
            changed[keyword] = value
            with self.subTest(early_mutation=keyword), self.assertRaisesRegex(ValueError, CP_BOOT_V3_MODULE_AUTHORITY):
                _accept_early_modules(EARLY_MODULE_ROWS_V3, **changed)
        _accept_kernel_config(KERNEL_CONFIG_ROWS_V3, release=EARLY_KERNEL_RELEASE_V3, config_sha256=EARLY_KERNEL_CONFIG_SHA256_V3)
        for index, (symbol, _value) in enumerate(KERNEL_CONFIG_ROWS_V3):
            absent = KERNEL_CONFIG_ROWS_V3[:index] + KERNEL_CONFIG_ROWS_V3[index + 1:]
            wrong_n = list(KERNEL_CONFIG_ROWS_V3)
            wrong_n[index] = (symbol, "n")
            wrong_value = list(KERNEL_CONFIG_ROWS_V3)
            wrong_value[index] = (symbol, "y" if KERNEL_CONFIG_ROWS_V3[index][1] == "m" else "m")
            for changed in (absent, tuple(wrong_n), tuple(wrong_value)):
                with self.subTest(config=symbol, value=changed), self.assertRaisesRegex(ValueError, CP_BOOT_V3_MODULE_AUTHORITY):
                    _accept_kernel_config(changed, release=EARLY_KERNEL_RELEASE_V3, config_sha256=EARLY_KERNEL_CONFIG_SHA256_V3)
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_MODULE_AUTHORITY):
            _accept_kernel_config(KERNEL_CONFIG_ROWS_V3, release="other", config_sha256=EARLY_KERNEL_CONFIG_SHA256_V3)

    def test_c_prefirewall_nic_socket_and_monitor_census(self) -> None:
        arguments = dict(
            cmdline=("quiet", "ip=off"),
            initial_nics=(("eth0", False, False, False),),
            final_nics=(("eth0", False, False, False),),
            inet_socket_count=0,
            packet_socket_count=0,
            monitor_sockets=(("AF_NETLINK", "NETLINK_ROUTE", "bound"),),
            enobufs=False,
            rxq_ovfl=False,
            ack_sequence_matches=True,
            dump_generation_contiguous=True,
            monitor_close_reopen=False,
            uncorrelated_event=False,
            final_queue=(),
        )
        _accept_prefirewall_network(**arguments)
        def _mutations():
            yield "cmdline", ("ip=off", "ip=off")
            yield "cmdline", ("ip=off", "rd.neednet")
            yield "cmdline", ("ip=off", "BOOTIF=01-00-11-22-33-44-55")
            yield "cmdline", ("ip=off", "net.ifnames=0")
            yield "initial_nics", (("eth0", True, False, False),)
            yield "initial_nics", (("eth0", False, True, False),)
            yield "initial_nics", (("eth0", False, False, True),)
            yield "final_nics", (("eth1", False, False, False),)
            yield "inet_socket_count", 1
            yield "packet_socket_count", 1
            yield "monitor_sockets", ()
            yield "monitor_sockets", (("AF_NETLINK", "NETLINK_ROUTE", "bound"), ("AF_NETLINK", "NETLINK_ROUTE", "bound"))
            yield "enobufs", True
            yield "rxq_ovfl", True
            yield "ack_sequence_matches", False
            yield "dump_generation_contiguous", False
            yield "monitor_close_reopen", True
            yield "uncorrelated_event", True
            yield "final_queue", ("uevent",)

        mutations = tuple(_mutations())
        for key, value in mutations:
            changed = dict(arguments)
            changed[key] = value
            with self.subTest(network_mutation=key), self.assertRaisesRegex(ValueError, CP_BOOT_V3_NETWORK_POLICY):
                _accept_prefirewall_network(**changed)

    def test_d_closed_control_readbacks_require_all_ten_rows(self) -> None:
        controls = _control_fixture()
        _accept_controls(controls)
        for name in CONTROL_NAMES_V3:
            changed = dict(controls)
            del changed[name]
            with self.subTest(missing=name), self.assertRaisesRegex(ValueError, CP_BOOT_V3_CONTROL):
                _accept_controls(changed)
        for name, entry in (("sysrq", ("0", 0, KERNEL_READBACK_IDENTITY_V3)), ("unprivileged_bpf", (3, 1, KERNEL_READBACK_IDENTITY_V3)), ("kernel_debug", ((2, 2), (1, 1), (4, 2), (3, 3), False, False, KERNEL_READBACK_IDENTITY_V3))):
            changed = dict(controls)
            changed[name] = entry
            with self.subTest(unparseable_or_wrong=name), self.assertRaisesRegex(ValueError, CP_BOOT_V3_CONTROL):
                _accept_controls(changed)
        for name, entry in (("modules", (0, 1, "foreign-kernel", True)), ("writable_roots", (WRITABLE_ROOT_REQUIREMENTS_V3, "foreign-mount-namespace")), ("tpm_closure", (TPM_CLOSURE_REQUIREMENTS_V3, "foreign-tpm-device"))):
            changed = dict(controls)
            changed[name] = entry
            with self.subTest(identity=name), self.assertRaisesRegex(ValueError, CP_BOOT_V3_CONTROL):
                _accept_controls(changed)

    def test_e_closed_dev_tree_checks_literal_and_registered_majors(self) -> None:
        nodes = _resolved_dev_rows(REGISTERED_MAJORS_V3)
        _accept_dev_tree(DEV_DIRECTORIES_V3, nodes, REGISTERED_MAJORS_V3, ())
        wrong_kind = list(nodes)
        wrong_kind[0] = (wrong_kind[0][0], "block", *wrong_kind[0][2:])
        wrong_mode = list(nodes)
        wrong_mode[1] = (*wrong_mode[1][:4], 0o600, *wrong_mode[1][5:])
        wrong_minor = list(nodes)
        wrong_minor[2] = (*wrong_minor[2][:3], 8, *wrong_minor[2][4:])
        wrong_owner = list(nodes)
        wrong_owner[7] = (*wrong_owner[7][:5], 1, 0)
        foreign = nodes + (("/dev/foreign", "char", 1, 3, 0o666, 0, 0),)
        for changed in (nodes[:-1], tuple(wrong_kind), tuple(wrong_mode), tuple(wrong_minor), tuple(wrong_owner), foreign):
            with self.assertRaisesRegex(ValueError, CP_BOOT_V3_DEV_TREE):
                _accept_dev_tree(DEV_DIRECTORIES_V3, changed, REGISTERED_MAJORS_V3, ())
        for forbidden in (("/dev/tpm0", "char"), ("/dev/dm-0", "char"), ("/dev/ttyS0", "char"), ("/dev/dri/card0", "char"), ("/dev/nvidia99", "char"), ("/dev/evil", "socket")):
            with self.subTest(forbidden=forbidden), self.assertRaisesRegex(ValueError, CP_BOOT_V3_DEV_TREE):
                _accept_dev_tree(DEV_DIRECTORIES_V3, nodes, REGISTERED_MAJORS_V3, (forbidden,))
        collision = dict(REGISTERED_MAJORS_V3)
        collision["nvidia_uvm"] = collision["nvidia_gpu"]
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_DEV_TREE):
            _accept_dev_tree(DEV_DIRECTORIES_V3, nodes, collision, ())
        changed_gpu = dict(REGISTERED_MAJORS_V3)
        changed_gpu["nvidia_gpu"] = 196
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_DEV_TREE):
            _accept_dev_tree(DEV_DIRECTORIES_V3, nodes, changed_gpu, ())
        one_gpu_neighbor_changed = list(nodes)
        one_gpu_neighbor_changed[7] = (*one_gpu_neighbor_changed[7][:2], 196, *one_gpu_neighbor_changed[7][3:])
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_DEV_TREE):
            _accept_dev_tree(DEV_DIRECTORIES_V3, tuple(one_gpu_neighbor_changed), changed_gpu, ())
        _accept_dev_tree(DEV_DIRECTORIES_V3, _resolved_dev_rows(changed_gpu), changed_gpu, ())

    def test_f_five_process_launch_inventory_and_terminal_exit_rule(self) -> None:
        roles = _launch_fixture()
        _accept_launch_inventory(roles)
        for name in tuple(roles):
            changed = dict(roles)
            del changed[name]
            with self.subTest(missing=name), self.assertRaisesRegex(ValueError, CP_BOOT_V3_LAUNCH_SUPERVISION):
                _accept_launch_inventory(changed)
        extra = dict(roles)
        extra["unexpected"] = (1, "long_lived", "network", "listener", "never")
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_LAUNCH_SUPERVISION):
            _accept_launch_inventory(extra)
        for name, entry in (("inference", (2, "long_lived", "loopback:127.0.0.1:8000", "one_listener", "never")), ("gateway", (1, "long_lived", "ra_tls_only", "one_listener", "never")), ("collector", ((0, 1), "transient", "no_network_listener", "pid1_spawn_reap_one_bounded_request_response", "always"))):
            changed = dict(roles)
            changed[name] = entry
            with self.subTest(launch_mutation=name), self.assertRaisesRegex(ValueError, CP_BOOT_V3_LAUNCH_SUPERVISION):
                _accept_launch_inventory(changed)
        _accept_long_lived_exit("gateway", ("ingress_close", "terminal_failure"))
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_LAUNCH_SUPERVISION):
            _accept_long_lived_exit("gateway", ("replacement_launch",))

    def test_g_resource_actions_capacities_and_saturation_boundaries(self) -> None:
        _accept_resource_inventory(RESOURCE_ACTIONS_V3, RESOURCE_CAPACITIES_V3)
        permits = _two_route_permits(RESOURCE_CAPACITIES_V3, ("inference", "asr"))
        self.assertEqual(len(permits), 2)
        self.assertEqual({len(permit) for permit in permits}, {2097152})
        self.assertEqual(sum(map(len, permits)), 4194304)
        self.assertEqual(_request_decision(("inference", "asr"), "inference"), "route_work_saturated")
        self.assertEqual(_session_decision(RESOURCE_CAPACITIES_V3, 4), "session_saturated")
        self.assertEqual(_session_decision(RESOURCE_CAPACITIES_V3, 3), "session_admitted")
        changed_stream = dict(RESOURCE_CAPACITIES_V3)
        changed_stream["stream_buffer_bytes"] = 1048576
        self.assertEqual({len(permit) for permit in _two_route_permits(changed_stream, ("inference", "asr"))}, {1048576})
        changed_sessions = dict(RESOURCE_CAPACITIES_V3)
        changed_sessions["max_live_sessions"] = 5
        self.assertEqual(_session_decision(changed_sessions, 4), "session_admitted")
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_RESOURCE_REDUCER):
            _accept_resource_inventory(RESOURCE_ACTIONS_V3, changed_stream)
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_RESOURCE_REDUCER):
            _accept_resource_inventory(RESOURCE_ACTIONS_V3[:-1], RESOURCE_CAPACITIES_V3)

    def test_h_wire_header_type_set_and_frame_sizes(self) -> None:
        self.assertEqual(WIRE_TYPES_V3, tuple((number, name) for number, name in enumerate(("SESSION_FD", "COLLECTOR_REQUEST", "COLLECTOR_RESPONSE", "COLLECTOR_ACK_VALID", "COLLECTOR_ACK_INVALID", "COLLECTOR_CANCEL", "REQUEST_ACQUIRE", "REQUEST_ADMIT", "REQUEST_REJECT", "WORK_BEGIN", "WORK_BEGUN", "WORK_FINISH", "WORK_FINISHED", "REQUEST_RELEASE", "REQUEST_RELEASED", "SESSION_RELEASE", "SESSION_RELEASED", "PRE_REQUEST_REJECTED", "GLOBAL_FAULT", "CHUNK_ACK", "SESSION_FD_ACK", "GATEWAY_READINESS_PROBE", "GATEWAY_READINESS_RESULT"), start=1)))
        self.assertEqual(struct.calcsize(HEADER_FORMAT_V3), HEADER_SIZE_V3)
        token = b"t" * 32
        header = _encode_header(6, START_FLAG_V3 | END_FLAG_V3, 7, 4, token)
        self.assertEqual(len(header), 72)
        self.assertEqual(_decode_header(header)[2], 6)
        for flags in range(8):
            self.assertEqual(_decode_header(_encode_header(6, flags, 1, 4, token))[3], flags)
        for flags in (-1, 8, 9):
            with self.subTest(flags=flags), self.assertRaises(ValueError):
                _encode_header(6, flags, 1, 4, token)
        with self.assertRaises(ValueError):
            _decode_header(header[:14] + b"\0\1" + header[16:])
        with self.assertRaises(ValueError):
            _encode_header(24, 0, 1, 4, token)
        self.assertEqual(len(struct.pack(">BB2s", 1, 1, b"\0\0")), 4)
        self.assertEqual(len(struct.pack(">B3sII32s", 1, b"\0\0\0", 1, 0, b"x" * 32)), 44)
        self.assertEqual(len(struct.pack(">B3sII32sH", 1, b"\0\0\0", 1, 0, b"x" * 32, 1)), 46)
        self.assertEqual(len(struct.pack(">QB3sI32s32s32s", 1, 1, b"\0\0\0", 2097152, b"a" * 32, b"b" * 32, b"c" * 32)), 112)
        self.assertEqual(len(struct.pack(">QHH4s32s32s32s", 1, 7, 1, b"\0" * 4, b"a" * 32, b"b" * 32, b"c" * 32)), 112)
        self.assertEqual(MAX_CHUNK_PAYLOAD_BYTES_V3, 16384)
        self.assertEqual((MAX_COLLECTOR_RESPONSE_BYTES_V3 + MAX_CHUNK_PAYLOAD_BYTES_V3 - 1) // MAX_CHUNK_PAYLOAD_BYTES_V3, 513)

    def test_i_serving_session_rows_deadlines_and_audio_boundaries(self) -> None:
        _accept_serving_session_rows(SERVING_SESSION_ROWS_V3, SERVING_DEADLINES_V3)
        with self.assertRaises(ValueError):
            _accept_serving_session_rows(SERVING_SESSION_ROWS_V3 + (SERVING_SESSION_ROWS_V3[-1],), SERVING_DEADLINES_V3)
        changed_deadlines = dict(SERVING_DEADLINES_V3)
        changed_deadlines["tls"] = 5
        with self.assertRaises(ValueError):
            _accept_serving_session_rows(SERVING_SESSION_ROWS_V3, changed_deadlines)
        self.assertEqual((_audio_branch(11534336), _audio_branch(11534337), _audio_branch(67108864), _audio_branch(67108865)), ("pass", "413_drain", "413_drain", "413_hard_close"))

    def test_j_failure_stages_tokens_and_phase_partition_are_discriminating(self) -> None:
        self.assertEqual(len(FAILURE_TOKENS_V3), 7)
        self.assertEqual(FAILURE_TOKENS_V3, ("authority", "binding", "pid1", "adapter", "root_transition", "runtime_authority", "serving_integrity"))
        _accept_failure_mapping(FAILURE_TRIGGER_MAPPING_V3)
        aliased = dict(FAILURE_TRIGGER_MAPPING_V3)
        aliased["first_root_map_through_c4_admission"] = "adapter"
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_FAILURE_PROTOCOL):
            _accept_failure_mapping(aliased)
        unmapped = dict(FAILURE_TRIGGER_MAPPING_V3)
        del unmapped["post_activation_identity_drift"]
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_FAILURE_PROTOCOL):
            _accept_failure_mapping(unmapped)
        unreachable = dict(FAILURE_TRIGGER_MAPPING_V3)
        unreachable["before_schema_selection"] = "binding"
        with self.assertRaisesRegex(ValueError, CP_BOOT_V3_FAILURE_PROTOCOL):
            _accept_failure_mapping(unreachable)

    def test_k_nine_v3_reason_codes_are_literal_and_complete(self) -> None:
        self.assertEqual(len(REASON_CODES_V3), 9)
        self.assertEqual({CP_BOOT_V3_PCR, CP_BOOT_V3_LATCH, CP_BOOT_V3_MODULE_AUTHORITY, CP_BOOT_V3_NETWORK_POLICY, CP_BOOT_V3_CONTROL, CP_BOOT_V3_DEV_TREE, CP_BOOT_V3_LAUNCH_SUPERVISION, CP_BOOT_V3_RESOURCE_REDUCER, CP_BOOT_V3_FAILURE_PROTOCOL}, REASON_CODES_V3)

    def test_z_no_v3_production_module_import(self) -> None:
        tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))
        imported = {node.module for node in ast.walk(tree) if isinstance(node, ast.ImportFrom) and node.module}
        banned = {
            "conf_proc_spp_boot_v3",
            "conf_proc_spp_boot_v3_tables",
            "conf_proc_spp_boot_v3_wire",
            "conf_proc_spp_boot_v3_resource",
            "conf_proc_spp_boot_dispatch_v3",
            "conf_proc_spp_boot_payload_v3",
            "conf_proc_spp_boot_payload_v3_inspect",
        }
        self.assertFalse(imported & banned)


if __name__ == "__main__":
    unittest.main(verbosity=2)
