#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Stable public failures for diagnostic input-closure manifest production."""

from __future__ import annotations

from typing import Final


CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW_COUNT: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW_COUNT"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH_ORDER: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH_ORDER"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_MISSING: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_MISSING"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_PAIRING: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_PAIRING"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_MANDATORY_ROLE: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_MANDATORY_ROLE"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_FORBIDDEN_PATH: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_FORBIDDEN_PATH"
CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW: Final = "CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW"

ALL_SPP_DIAG_INPUT_CLOSURE_MANIFEST_REASONS: Final = frozenset(
    {
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW_COUNT,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH_ORDER,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_MISSING,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_CONTROL_PLAN_PAIRING,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_MANDATORY_ROLE,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_PATH,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_FORBIDDEN_PATH,
        CP_SPP_DIAG_INPUT_CLOSURE_MANIFEST_ROW,
    }
)


class SppDiagInputClosureManifestError(RuntimeError):
    """One stable public input-closure manifest production reason code."""

    def __init__(self, reason_code: str) -> None:
        if reason_code not in ALL_SPP_DIAG_INPUT_CLOSURE_MANIFEST_REASONS:
            raise ValueError("unknown SPP diagnostic input-closure manifest reason")
        self.reason_code = reason_code
        super().__init__(reason_code)
