#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Closed literal inventories for the SPP boot authority v3."""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Final

from conf_proc_spp_boot import BOOTSTRAP_MOUNTS_V2


# BOOTSTRAP_MOUNTS_V2 is public and remains the v3 bootstrap mount authority
# so the shared properties cannot silently drift.
BOOTSTRAP_MOUNTS_V3: Final = BOOTSTRAP_MOUNTS_V2

EARLY_MODULE_TARGET_KERNEL_RELEASE_V3: Final = "6.8.0-1058-azure-fde"
EARLY_MODULE_TARGET_CONFIG_SHA256_V3: Final = (
    "1ce93dd4569a7607db57f2b3321d38d0e0122fe29efa430374c3717ccbde68b9"
)
EARLY_MODULE_SIGNER_V3: Final = "Build time autogenerated kernel key"
EARLY_MODULE_SIGNATURE_KEY_ID_V3: Final = (
    "4C:F4:E0:34:2A:28:95:F1:5C:29:6C:20:CC:25:FC:B8:61:8D:B5:24"
)
EARLY_MODULE_RELEASE_ROOT_V3: Final = "/lib/modules/6.8.0-1058-azure-fde/"


@dataclass(frozen=True)
class EarlyModuleRowV3:
    path: str
    sha256: str


EARLY_MODULE_ROWS_V3: Final = (
    EarlyModuleRowV3(
        "kernel/drivers/md/dm-bufio.ko",
        "318df552f245da0e3bce5c047443f349d3771f044bfd9573ebe486a9056d107c",
    ),
    EarlyModuleRowV3(
        "kernel/drivers/md/dm-verity.ko",
        "31f7c5f1832ed81d4fa9290396d559b6e82d68eadb2df8b157fb71968431b6dc",
    ),
    EarlyModuleRowV3(
        "kernel/lib/libcrc32c.ko",
        "de152f89a11624f60b5c2ab74ff2bda86a1a8ecc7d110b37147e61abd5ab3c63",
    ),
    EarlyModuleRowV3(
        "kernel/net/netfilter/nfnetlink.ko",
        "b5eea11e088608fd57efaa8baf6059df9d4b0182df091bd2af7f686530cc69d3",
    ),
    EarlyModuleRowV3(
        "kernel/net/netfilter/nf_tables.ko",
        "2ea6941010d02f6c548fc259be178289a47698859ac9e6bcbbb30426bfd16589",
    ),
)
EARLY_MODULE_BUILTIN_DEPENDENCIES_V3: Final = (
    "crc32c_intel",
    "crc32c_generic",
)


@dataclass(frozen=True)
class KernelConfigBindingRowV3:
    symbol: str
    expected_value: str


KERNEL_CONFIG_BINDING_ROWS_V3: Final = (
    KernelConfigBindingRowV3("CONFIG_DEVTMPFS", "y"),
    KernelConfigBindingRowV3("CONFIG_BLK_DEV_NVME", "y"),
    KernelConfigBindingRowV3("CONFIG_BLK_DEV_DM", "y"),
    KernelConfigBindingRowV3("CONFIG_SQUASHFS", "y"),
    KernelConfigBindingRowV3("CONFIG_TCG_TPM", "y"),
    KernelConfigBindingRowV3("CONFIG_TCG_CRB", "y"),
    KernelConfigBindingRowV3("CONFIG_NETFILTER", "y"),
    KernelConfigBindingRowV3("CONFIG_DM_VERITY", "m"),
    KernelConfigBindingRowV3("CONFIG_NF_TABLES", "m"),
)
# Moving a named m capability to y requires a different fully bound v3
# contract; this literal table is intentionally not a compatibility policy.


@dataclass(frozen=True)
class ControlValueRuleV3:
    path: str
    accepted_pre_values: tuple[int, ...] | None
    accepted_pre_range: tuple[int, int] | None
    accepted_post_values: tuple[int, ...] | None
    post_formula: str | None


@dataclass(frozen=True)
class ControlInventoryRowV3:
    name: str
    value_rules: tuple[ControlValueRuleV3, ...]
    paired_requirements: tuple[str, ...]
    stage1_only_requirements: tuple[str, ...]


CONTROL_INVENTORY_ROWS_V3: Final = (
    ControlInventoryRowV3(
        "modules",
        (ControlValueRuleV3(
            "/proc/sys/kernel/modules_disabled", (0,), None, (1,), None,
        ),),
        ("deny_module_load_afterward",),
        (),
    ),
    ControlInventoryRowV3(
        "kexec",
        (ControlValueRuleV3(
            "/proc/sys/kernel/kexec_load_disabled", (0, 1), None, (1,), None,
        ),),
        (
            "/sys/kernel/security/lockdown=integrity_or_confidentiality",
            "deny_kexec_load_afterward",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "sysrq",
        (ControlValueRuleV3(
            "/proc/sys/kernel/sysrq", None, (0, 511), (0,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "unprivileged_bpf",
        (ControlValueRuleV3(
            "/proc/sys/kernel/unprivileged_bpf_disabled", (0, 1, 2), None, (1,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "userfaultfd",
        (ControlValueRuleV3(
            "/proc/sys/vm/unprivileged_userfaultfd", (0, 1), None, (0,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "kernel_debug",
        (
            ControlValueRuleV3("/proc/sys/kernel/kptr_restrict", (0, 1, 2), None, (2,), None),
            ControlValueRuleV3("/proc/sys/kernel/dmesg_restrict", (0, 1), None, (1,), None),
            ControlValueRuleV3(
                "/proc/sys/kernel/perf_event_paranoid", (-1, 0, 1, 2, 3, 4), None,
                (3, 4), "max(pre,3)",
            ),
            ControlValueRuleV3("/proc/sys/kernel/yama/ptrace_scope", (0, 1, 2, 3), None, (3,), None),
        ),
        ("debugfs_absent_after_handoff", "proc_kcore_inaccessible_to_serving_identities"),
        ("debugfs", "/proc/kcore"),
    ),
    ControlInventoryRowV3(
        "recovery_operator_ingress",
        (),
        (
            "cmdline_absent:init=",
            "cmdline_absent:rd.break",
            "cmdline_absent:systemd.unit=",
            "cmdline_absent:systemd.debug_shell",
            "cmdline_absent:rescue",
            "cmdline_absent:emergency",
            "cmdline_absent:recovery",
            "no_getty_or_serial_reader",
            "no_ssh",
            "no_azure_agent",
            "no_run_command_or_extension_agent",
            "no_cloud_init",
            "no_container_socket",
            "no_interactive_process_or_listener",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "writable_roots",
        (),
        (
            "root_and_model_mappings_read_only",
            "ordinary_tmpfs=nosuid,nodev,noexec",
            "at_most_one_declared_jit_tmpfs=nosuid,nodev",
            "no_other_writable_executable_disk_backed_or_bind_backed_mount",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "tpm_closure",
        (),
        (
            "one_measured_attestation_broker_retains_pinned_tpm_resource_manager_after_pcr15_extend",
            "attestation_broker_exposes_quote_and_pcr_read_only_on_root_owned_unix_socket",
            "pid1_gateway_collector_model_processes_have_no_tpm_fd_device_path_or_capability",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "persistence",
        (),
        (
            "/proc/swaps_has_no_row",
            "kdump_absent",
            "coredumps_disabled",
            "content_bearing_persistent_journaling_absent",
            "no_writable_block_device_mounted",
            "writable_log_request_cache_roots_are_declared_reboot_ephemeral_tmpfs",
        ),
        (),
    ),
)


@dataclass(frozen=True)
class DevDirectoryRowV3:
    path: str
    mode: int
    uid: int
    gid: int


@dataclass(frozen=True)
class DevTreeRowV3:
    path: str
    kind: str
    major_kind: str
    major_or_registration_key: int | str
    minor: int
    mode: int
    uid: int | None
    gid: int | None
    identity_binding: str | None


DEV_TREE_DIRECTORY_ROWS_V3: Final = (
    DevDirectoryRowV3("/dev", 0o755, 0, 0),
    DevDirectoryRowV3("/dev/nvidia-caps", 0o755, 0, 0),
)
DEV_TREE_ROWS_V3: Final = (
    DevTreeRowV3("/dev/console", "char", "literal", 5, 1, 0o600, 0, 0, None),
    DevTreeRowV3("/dev/null", "char", "literal", 1, 3, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/zero", "char", "literal", 1, 5, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/full", "char", "literal", 1, 7, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/random", "char", "literal", 1, 8, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/urandom", "char", "literal", 1, 9, 0o666, 0, 0, None),
    DevTreeRowV3(
        "/dev/tpmrm0", "char", "registered", "tpm_rm", 65536, 0o660,
        None, None, "sealed_attestation_broker",
    ),
    DevTreeRowV3("/dev/nvidia0", "char", "registered", "nvidia_gpu", 0, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidiactl", "char", "registered", "nvidia_gpu", 255, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-uvm", "char", "registered", "nvidia_uvm", 0, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-uvm-tools", "char", "registered", "nvidia_uvm", 1, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-caps/nvidia-cap1", "char", "registered", "nvidia_caps", 1, 0o400, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-caps/nvidia-cap2", "char", "registered", "nvidia_caps", 2, 0o400, 0, 0, None),
)
DEV_TREE_FORBIDDEN_PATH_PATTERNS_V3: Final = (
    "/dev/tpm0",
    "/dev/mapper/control",
    "/dev/dm-*",
    "any_block_device",
    "/dev/tty*",
    "/dev/ptmx",
    "/dev/pts*",
    "/dev/kmsg",
    "memory_device",
    "/dev/dri/*",
    "undeclared_nvidia_node",
)
DEV_TREE_FORBIDDEN_NODE_KINDS_V3: Final = (
    "symlink",
    "regular_file",
    "socket",
    "fifo",
    "submount",
)


FAILURE_DIAGNOSTIC_TOKENS_V3: Final = (
    "authority",
    "binding",
    "pid1",
    "adapter",
    "root_transition",
    "runtime_authority",
    "serving_integrity",
)
FAILURE_LATE_CODES_V3: Final = ("network_close", "poweroff_returned")
FAILURE_STAGES_V3: Final = (
    "diagnostic",
    "close_serving_network",
    "poweroff_requested",
    "fail_stop",
)


@dataclass(frozen=True)
class LaunchFdRowV3:
    fd: int
    purpose: str
    owner: str
    inheritance: str
    limit: str


@dataclass(frozen=True)
class PipeCensusRowV3:
    fd: int
    stream: str
    requested_capacity_bytes: int
    minimum_readback_capacity_bytes: int
    census_budget_bytes: int
    detection_bytes: int
    disposition: str


@dataclass(frozen=True)
class ReadinessProtocolRowV3:
    transport: str
    request_magic: bytes
    result_magic: bytes
    request_bytes: int
    result_bytes: int
    role_id: int | None
    clock: str
    deadline_unit: str
    credentials: str
    ancillary_fd_rule: str
    aggregate_deadline_seconds: int | None


@dataclass(frozen=True)
class ReadinessLayoutFieldV3:
    offset: int
    width: int
    name: str
    encoding: str
    constraint: str


@dataclass(frozen=True)
class ReadinessLayoutRowV3:
    row_id: str
    transport: str
    total_bytes: int
    fields: tuple[ReadinessLayoutFieldV3, ...]
    credential_rule: str
    fd_rule: str
    trailing_rule: str


@dataclass(frozen=True)
class ReadinessBarrierRowV3:
    row_id: str
    role_order: tuple[str, ...]
    generation: int
    census_cardinality: int
    deadline_clock: str
    deadline_delta_ns: int
    states: tuple[str, ...]
    terminal_event_order: str
    completion_rule: str
    consume_rule: str
    retry_rule: str


@dataclass(frozen=True)
class LaunchRoleRowV3:
    role: str
    source_path: str
    process_kind: str
    interpreter_path: str
    argv: tuple[str, ...]
    expected_network_scope: str
    expected_process_capabilities: tuple[str, ...]
    expected_capability_bounding_set: tuple[str, ...]
    expected_ambient_capabilities: tuple[str, ...]
    expected_no_new_privileges: bool
    uid: int
    gid: int
    supplementary_groups: tuple[int, ...]
    environment: tuple[tuple[str, str], ...]
    cwd: str
    root: str
    namespace_requirements: tuple[str, ...]
    cardinality: str
    child_fork_policy: str
    restart_policy: str
    fd_surface: tuple[LaunchFdRowV3, ...]
    pipe_census: tuple[PipeCensusRowV3, ...]
    listener_policy: str
    upstream_policy: str
    admission_policy: str
    readiness: ReadinessProtocolRowV3 | None


@dataclass(frozen=True)
class Stage2FdRowV3:
    fd: int
    purpose: str
    pre_exec_cloexec: str
    stage2_action: str
    terminal_owner: str


@dataclass(frozen=True)
class Stage2Pid1IdentityRowV3:
    row_id: str
    source_path: str
    interpreter_path: str
    argv: tuple[str, ...]
    environment: tuple[tuple[str, str], ...]
    pid: int
    ppid: int
    uid: int
    gid: int
    supplementary_groups: tuple[int, ...]
    cwd: str
    root: str
    proc_self_exe_identity: str
    argv0_identity: str
    signal_reap_row_id: str


@dataclass(frozen=True)
class Stage2TaskLocalStateV3:
    view: str
    pid: int
    tid: int
    tgid: int
    generation: str
    effective: tuple[str, ...]
    permitted: tuple[str, ...]
    inheritable: tuple[str, ...]
    ambient: tuple[str, ...]
    bounding: tuple[str, ...]
    signal_blocked: tuple[str, ...]
    signal_ignored: tuple[str, ...]
    signal_caught: tuple[str, ...]
    signal_pending: tuple[str, ...]
    shared_pending: tuple[str, ...]


@dataclass(frozen=True)
class Stage2ThreadCensusRowV3:
    row_id: str
    event_anchor: str
    proc_task_entries: tuple[str, ...]
    task_pid: int
    task_tgid: int
    process_state: Stage2TaskLocalStateV3
    task_state: Stage2TaskLocalStateV3


@dataclass(frozen=True)
class Stage2CapabilityPhaseRowV3:
    row_id: str
    event_anchor: str
    effective: tuple[str, ...]
    permitted: tuple[str, ...]
    inheritable: tuple[str, ...]
    ambient: tuple[str, ...]
    bounding: tuple[str, ...]
    securebits: int


@dataclass(frozen=True)
class Stage2ExecFdAuthorityRowV3:
    fd: int
    role: str
    object_identity: str
    creation_flags: tuple[str, ...]
    status_flags: tuple[str, ...]
    descriptor_flag_rule: str
    owner: str
    stage2_action: str
    terminal_owner: str
    issuable: bool
    mechanism: str | None
    protocol: str | None
    multicast_groups: tuple[str, ...] | None
    queue_capacity: int | None
    credentials: str | None
    loss_counter: str | None
    receive_capability: str | None
    fdinfo_expectation: str | None


@dataclass(frozen=True)
class Stage2FdCensusEntryV3:
    fd: int
    role: str
    owner: str
    descriptor_flags: tuple[str, ...]
    status_flags: tuple[str, ...]
    object_identity: str
    generation: str
    logical_only: bool


@dataclass(frozen=True)
class Stage2FdCensusRowV3:
    row_id: str
    event_anchor: str
    entries: tuple[Stage2FdCensusEntryV3, ...]
    total: int
    logical_only_roles: tuple[str, ...]


@dataclass(frozen=True)
class Stage2SignalReapRowV3:
    row_id: str
    mask_install_operation: str
    mask_install_cardinality: int
    mask_install_phase: str
    blocked_signals: tuple[str, ...]
    ignored_signals: tuple[str, ...]
    caught_signals: tuple[str, ...]
    sigchld_disposition: str
    sigchld_flags: tuple[str, ...]
    forbidden_sigchld_flags: tuple[str, ...]
    other_catchable_disposition: str
    signalfd_flags: tuple[str, ...]
    signalfd_mask: tuple[str, ...]
    waiter_owner: str
    epoll_owner: str
    forbidden_consumers: tuple[str, ...]
    waitid_selector: str
    waitid_flags: tuple[str, ...]
    waitid_empty_outcomes: tuple[str, ...]
    signalfd_drain_terminal: str
    signalfd_record_rule: str
    signalfd_code_allowlist: tuple[str, ...]
    signalfd_invalid_rule: str
    stop_continue_rule: str
    reap_schedule_rule: str
    reap_identity_rule: str
    proc_closure_rule: str
    child_reset_requirements: tuple[str, ...]


@dataclass(frozen=True)
class Stage2SignalOutcomeRowV3:
    signal: str
    member: str
    epoch_binding: str
    transition: str


@dataclass(frozen=True)
class ControllerTerminalEpochV3:
    row_id: str
    triggers: tuple[str, ...]
    atomic_owner: str
    actions: tuple[str, ...]
    duplicate_rule: str
    epoll_batch_order: str
    completion_compare_rule: str
    collector_exception_rule: str


@dataclass(frozen=True)
class Stage2LogicalTraceAuthorityRowV3:
    row_id: str
    intended_fd: int
    package_selected: bool
    issuable: bool
    mechanism: str | None
    protocol: str | None
    multicast_groups: tuple[str, ...] | None
    queue_capacity: int | None
    credentials: str | None
    loss_counter: str | None
    receive_capability: str | None
    fdinfo_expectation: str | None


@dataclass(frozen=True)
class Stage2Pid1AuthorityV3:
    identity: Stage2Pid1IdentityRowV3
    thread_censuses: tuple[Stage2ThreadCensusRowV3, ...]
    child_fork_leaf: str
    forbidden_thread_creators: tuple[str, ...]
    interval_trace_requirement: str
    capability_phases: tuple[Stage2CapabilityPhaseRowV3, ...]
    capability_drop_sequence: tuple[str, ...]
    exec_fds: tuple[Stage2ExecFdAuthorityRowV3, ...]
    stdio_ofd_distinctness_checks: tuple[str, ...]
    fd_censuses: tuple[Stage2FdCensusRowV3, ...]
    signal_reap: Stage2SignalReapRowV3
    signal_outcomes: tuple[Stage2SignalOutcomeRowV3, ...]
    terminal_transition: ControllerTerminalEpochV3
    logical_trace: Stage2LogicalTraceAuthorityRowV3


@dataclass(frozen=True)
class Stage2ControllerRowV3:
    source_path: str
    source_size_bytes: int
    source_sha256: str
    interpreter_path: str
    argv: tuple[str, ...]
    environment: tuple[tuple[str, str], ...]
    uid: int
    gid: int
    supplementary_groups: tuple[int, ...]
    cwd: str
    root: str
    namespace_requirements: tuple[str, ...]
    exec_fd_census: tuple[Stage2FdRowV3, ...]
    fd_transition_requirements: tuple[str, ...]
    entitlement_dns: tuple[tuple[str, str], ...]
    entitlement_nftables: tuple[tuple[str, str], ...]
    entitlement_ledger_states: tuple[str, ...]
    initial_capabilities: tuple[str, ...]
    steady_capabilities: tuple[str, ...]
    pid1_authority: Stage2Pid1AuthorityV3


_FIXED_ROLE_ENVIRONMENT_V3: Final = (
    ("LANG", "C"),
    ("LC_ALL", "C"),
    ("PATH", "/nonexistent"),
    ("PYTHONNOUSERSITE", "1"),
    ("PYTHONDONTWRITEBYTECODE", "1"),
)
_ROLE_NAMESPACES_V3: Final = (
    "same_initial_user_namespace_as_stage2_pid1",
    "same_initial_pid_namespace_as_stage2_pid1",
    "same_initial_mount_namespace_as_stage2_pid1",
    "same_initial_network_namespace_as_stage2_pid1",
)
_ROLE_PIPE_CENSUS_V3: Final = (
    PipeCensusRowV3(1, "stdout", 65536, 65536, 65536, 1, "pid1_epoll_immediate_discard"),
    PipeCensusRowV3(2, "stderr", 65536, 65536, 65536, 1, "pid1_epoll_immediate_discard"),
)


def _python_role_argv_v3(role: str) -> tuple[str, ...]:
    return (
        "/usr/bin/python3.10", "-I", "-B", "-S",
        "/usr/lib/spp/conf_proc_spp_role_bootstrap.py", "--role=" + role,
    )


def _long_lived_readiness_v3(role_id: int) -> ReadinessProtocolRowV3:
    return ReadinessProtocolRowV3(
        "AF_UNIX SOCK_SEQPACKET root_owned", b"SPPRDQ3\0", b"SPPRDR3\0", 32, 80,
        role_id, "CLOCK_MONOTONIC", "nanoseconds", "one_matching_SCM_CREDENTIALS",
        "no_ancillary_fd", 4,
    )


READINESS_LAYOUT_ROWS_V3: Final = (
    ReadinessLayoutRowV3(
        "role_probe", "AF_UNIX SOCK_SEQPACKET root_owned", 32,
        (
            ReadinessLayoutFieldV3(0, 8, "magic", "bytes", "SPPRDQ3_then_NUL"),
            ReadinessLayoutFieldV3(8, 2, "version", "u16_be", "3"),
            ReadinessLayoutFieldV3(10, 2, "role_id", "u16_be", "1_to_3_exact_role"),
            ReadinessLayoutFieldV3(12, 4, "flags", "u32_be", "zero"),
            ReadinessLayoutFieldV3(16, 8, "generation", "u64_be", "shared_exact_1"),
            ReadinessLayoutFieldV3(24, 8, "deadline", "u64_be", "shared_absolute_CLOCK_MONOTONIC_ns"),
        ),
        "one_matching_SCM_CREDENTIALS", "no_ancillary_fd", "no_trailing_bytes",
    ),
    ReadinessLayoutRowV3(
        "role_result", "AF_UNIX SOCK_SEQPACKET root_owned", 80,
        (
            ReadinessLayoutFieldV3(0, 8, "magic", "bytes", "SPPRDR3_then_NUL"),
            ReadinessLayoutFieldV3(8, 2, "version", "u16_be", "3"),
            ReadinessLayoutFieldV3(10, 2, "role_id", "u16_be", "1_to_3_exact_role"),
            ReadinessLayoutFieldV3(12, 4, "flags", "u32_be", "exactly_1_ready"),
            ReadinessLayoutFieldV3(16, 8, "generation", "u64_be", "echo_shared_exact_1"),
            ReadinessLayoutFieldV3(24, 8, "deadline", "u64_be", "echo_shared_absolute_deadline"),
            ReadinessLayoutFieldV3(32, 4, "pid", "u32_be", "exact_supervised_child"),
            ReadinessLayoutFieldV3(36, 4, "uid", "u32_be", "exact_role_uid"),
            ReadinessLayoutFieldV3(40, 4, "gid", "u32_be", "exact_role_gid"),
            ReadinessLayoutFieldV3(44, 4, "reserved", "u32_be", "zero"),
            ReadinessLayoutFieldV3(48, 32, "executable_sha256", "bytes", "exact_measured_source_digest"),
        ),
        "one_matching_SCM_CREDENTIALS", "no_ancillary_fd", "no_trailing_bytes",
    ),
    ReadinessLayoutRowV3(
        "gateway_probe", "serving_wire_v3", 88,
        (
            ReadinessLayoutFieldV3(0, 72, "serving_wire_header", "bytes", "type_22_zero_session_single_chunk_no_fd"),
            ReadinessLayoutFieldV3(72, 8, "generation", "u64_be", "shared_exact_1"),
            ReadinessLayoutFieldV3(80, 8, "deadline", "u64_be", "shared_absolute_CLOCK_MONOTONIC_ns"),
        ),
        "authenticated_supervised_sender", "no_ancillary_fd", "no_trailing_bytes",
    ),
    ReadinessLayoutRowV3(
        "gateway_result", "serving_wire_v3", 128,
        (
            ReadinessLayoutFieldV3(0, 72, "serving_wire_header", "bytes", "type_23_zero_session_single_chunk_no_fd"),
            ReadinessLayoutFieldV3(72, 8, "generation", "u64_be", "echo_shared_exact_1"),
            ReadinessLayoutFieldV3(80, 4, "pid", "u32_be", "exact_supervised_gateway"),
            ReadinessLayoutFieldV3(84, 2, "worker_count", "u16_be", "0_to_4_equals_live_session_ledger"),
            ReadinessLayoutFieldV3(86, 2, "flags", "u16_be", "exactly_1_control_ready"),
            ReadinessLayoutFieldV3(88, 32, "executable_sha256", "bytes", "exact_measured_gateway_digest"),
            ReadinessLayoutFieldV3(120, 8, "control_endpoint_SO_COOKIE", "u64_be", "exact_nonzero"),
        ),
        "one_matching_SCM_CREDENTIALS", "no_ancillary_fd", "no_trailing_bytes",
    ),
)


READINESS_BARRIER_ROWS_V3: Final = (
    ReadinessBarrierRowV3(
        "all_four_generation_deadline",
        ("attestation-broker", "inference", "asr", "gateway"),
        1,
        1,
        "CLOCK_MONOTONIC",
        4_000_000_000,
        ("unstarted", "collecting", "candidate", "complete", "consumed", "failed"),
        "signalfd_and_reap_before_readiness_in_same_epoll_batch",
        "one_compare_and_set_collecting_to_complete_same_epoch_nonterminal",
        "one_exact_completion_makes_serving_eligible_then_duplicate_fails",
        "failed_census_is_terminal_no_retry_or_second_census",
    ),
)


LAUNCH_DELETE_WITNESS_ROWS_V3: Final = (
    "independent_coherent_delete",
)


LAUNCH_ROLE_ROWS_V3: Final = (
    LaunchRoleRowV3(
        "attestation-broker", "/usr/lib/spp/conf_proc_spp_attestation_broker.py", "interpreter",
        "/usr/bin/python3.10", _python_role_argv_v3("attestation-broker"), "none", (), (), (), True,
        61100, 61100, (), _FIXED_ROLE_ENVIRONMENT_V3, "/", "/", _ROLE_NAMESPACES_V3,
        "one_long_lived", "none", "never",
        (
            LaunchFdRowV3(0, "/dev/null", "pid1", "inherited", "exact"),
            LaunchFdRowV3(1, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(2, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(3, "root_owned_broker_SOCK_SEQPACKET", "pid1", "inherited", "sole_control_endpoint"),
            LaunchFdRowV3(4, "/dev/tpmrm0_resource_manager", "stage1", "fd5_transfer", "sole_pinned_tpm_handle"),
        ), _ROLE_PIPE_CENSUS_V3, "no_listener", "no_network", "none", _long_lived_readiness_v3(1),
    ),
    LaunchRoleRowV3(
        "inference", "/usr/lib/spp/conf_proc_spp_inference.py", "interpreter",
        "/usr/bin/python3.10", _python_role_argv_v3("inference"), "loopback", (), (), (), True,
        61101, 61101, (), _FIXED_ROLE_ENVIRONMENT_V3, "/", "/", _ROLE_NAMESPACES_V3,
        "one_long_lived", "none", "never",
        (
            LaunchFdRowV3(0, "/dev/null", "pid1", "inherited", "exact"),
            LaunchFdRowV3(1, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(2, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(3, "loopback_listener_127.0.0.1:8000", "pid1", "inherited", "sole_listener"),
            LaunchFdRowV3(4, "root_owned_readiness_SOCK_SEQPACKET", "pid1", "inherited", "sole_readiness_endpoint"),
        ), _ROLE_PIPE_CENSUS_V3, "one_pid1_created_loopback_listener_127.0.0.1:8000", "none", "none", _long_lived_readiness_v3(2),
    ),
    LaunchRoleRowV3(
        "asr", "/usr/lib/spp/asr_shim.py", "interpreter",
        "/usr/bin/python3.10", _python_role_argv_v3("asr"), "loopback", (), (), (), True,
        61102, 61102, (), _FIXED_ROLE_ENVIRONMENT_V3, "/", "/", _ROLE_NAMESPACES_V3,
        "one_long_lived", "none", "never",
        (
            LaunchFdRowV3(0, "/dev/null", "pid1", "inherited", "exact"),
            LaunchFdRowV3(1, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(2, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(3, "loopback_listener_127.0.0.1:8100", "pid1", "inherited", "sole_listener"),
            LaunchFdRowV3(4, "root_owned_readiness_SOCK_SEQPACKET", "pid1", "inherited", "sole_readiness_endpoint"),
        ), _ROLE_PIPE_CENSUS_V3, "one_pid1_created_loopback_listener_127.0.0.1:8100", "none", "none", _long_lived_readiness_v3(3),
    ),
    LaunchRoleRowV3(
        "gateway", "/usr/lib/spp/ratls_gateway.py", "interpreter",
        "/usr/bin/python3.10", _python_role_argv_v3("gateway"), "loopback", (), (), (), True,
        61103, 61103, (), _FIXED_ROLE_ENVIRONMENT_V3, "/", "/", _ROLE_NAMESPACES_V3,
        "one_long_lived", "none", "never",
        (
            LaunchFdRowV3(0, "/dev/null", "pid1", "inherited", "exact"),
            LaunchFdRowV3(1, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(2, "bounded_content_discard_pipe", "pid1", "inherited", "65536_plus_detection"),
            LaunchFdRowV3(3, "pid1_created_gateway_control_endpoint", "pid1", "inherited", "sole_control_endpoint"),
        ), _ROLE_PIPE_CENSUS_V3, "no_listener", "connect_only_loopback_127.0.0.1:8000_and_127.0.0.1:8100_after_work_permit", "pid1_admitted_connected_fds_and_pid1_entitlement_fd_only", None,
    ),
    # COHERENT_DELETE_COLLECTOR_START
    LaunchRoleRowV3(
        "collector", "/usr/lib/spp/ratls_collector.py", "interpreter",
        "/usr/bin/python3.10", _python_role_argv_v3("collector"), "none", (), (), (), True,
        61104, 61104, (), _FIXED_ROLE_ENVIRONMENT_V3, "/", "/", _ROLE_NAMESPACES_V3,
        "zero_or_one_transient", "none", "never",
        (
            LaunchFdRowV3(0, "one_request_stdin_pipe", "pid1", "inherited", "exact_one_request"),
            LaunchFdRowV3(1, "bounded_stdout_pipe", "pid1", "inherited", "8388608_plus_detection"),
            LaunchFdRowV3(2, "bounded_stderr_pipe", "pid1", "inherited", "65536_plus_detection"),
        ),
        (
            PipeCensusRowV3(1, "stdout", 8388608, 8388608, 8388608, 1, "collector_result_only"),
            PipeCensusRowV3(2, "stderr", 65536, 65536, 65536, 1, "immediate_discard"),
        ), "no_listener", "no_network", "pid1_spawned_reaped_one_bounded_request_response", None,
    ),
    # COHERENT_DELETE_COLLECTOR_END
)


_STAGE2_PID1_ARGV_V3: Final = (
    "python3.10", "-I", "-B", "-S", "/usr/lib/spp/conf_proc_spp_init.py",
    "--stage2", "--handoff-fd=3", "--device-monitor-fd=4",
    "--broker-tpm-fd=5",
)
_STAGE2_INITIAL_CAPABILITIES_V3: Final = (
    "CAP_KILL", "CAP_NET_ADMIN", "CAP_NET_BIND_SERVICE", "CAP_SETGID",
    "CAP_SETPCAP", "CAP_SETUID", "CAP_SYS_BOOT", "CAP_SYS_PTRACE",
)
_STAGE2_STEADY_CAPABILITIES_V3: Final = (
    "CAP_KILL", "CAP_NET_ADMIN", "CAP_SETGID", "CAP_SETUID", "CAP_SYS_BOOT",
    "CAP_SYS_PTRACE",
)
_STAGE2_SIGNAL_MASK_V3: Final = (
    "SIGCHLD", "SIGTERM", "SIGINT", "SIGHUP", "SIGQUIT",
)


def _stage2_pid1_state_v3(
    view: str,
    capabilities: tuple[str, ...],
    blocked: tuple[str, ...],
    ignored: tuple[str, ...],
) -> Stage2TaskLocalStateV3:
    return Stage2TaskLocalStateV3(
        view, 1, 1, 1, "controller_generation_1:start_time_boot_pid1",
        capabilities, capabilities, (), (), capabilities, blocked, ignored, (),
        (), (),
    )


_STAGE2_PID1_PREMASK_PROCESS_STATE_V3: Final = _stage2_pid1_state_v3(
    "process:/proc/1/status", _STAGE2_INITIAL_CAPABILITIES_V3, (), (),
)
_STAGE2_PID1_PREMASK_TASK_STATE_V3: Final = _stage2_pid1_state_v3(
    "task:/proc/1/task/1/status", _STAGE2_INITIAL_CAPABILITIES_V3, (), (),
)
_STAGE2_PID1_INITIAL_PROCESS_STATE_V3: Final = _stage2_pid1_state_v3(
    "process:/proc/1/status", _STAGE2_INITIAL_CAPABILITIES_V3,
    _STAGE2_SIGNAL_MASK_V3, ("SIGPIPE",),
)
_STAGE2_PID1_INITIAL_TASK_STATE_V3: Final = _stage2_pid1_state_v3(
    "task:/proc/1/task/1/status", _STAGE2_INITIAL_CAPABILITIES_V3,
    _STAGE2_SIGNAL_MASK_V3, ("SIGPIPE",),
)
_STAGE2_PID1_STEADY_PROCESS_STATE_V3: Final = _stage2_pid1_state_v3(
    "process:/proc/1/status", _STAGE2_STEADY_CAPABILITIES_V3,
    _STAGE2_SIGNAL_MASK_V3, ("SIGPIPE",),
)
_STAGE2_PID1_STEADY_TASK_STATE_V3: Final = _stage2_pid1_state_v3(
    "task:/proc/1/task/1/status", _STAGE2_STEADY_CAPABILITIES_V3,
    _STAGE2_SIGNAL_MASK_V3, ("SIGPIPE",),
)

_STAGE2_EXEC_FD_AUTHORITY_ROWS_V3: Final = (
    Stage2ExecFdAuthorityRowV3(
        0, "stdin", "/dev/null_char_1:3", ("O_RDONLY",), ("O_RDONLY",),
        "non_CLOEXEC", "stage2_pid1", "retain_standard", "stage2_pid1", True,
        "separate_open", "character_device", (), None, "root_pid1", None,
        None, "exact_device_inode_owner_flags",
    ),
    Stage2ExecFdAuthorityRowV3(
        1, "stdout_evidence", "/dev/console_char_5:1",
        ("O_WRONLY", "O_NOCTTY", "O_NONBLOCK"),
        ("O_WRONLY", "O_NONBLOCK"), "non_CLOEXEC", "stage2_pid1",
        "framed_evidence_only", "stage2_pid1", True, "separate_open",
        "character_device", (), None, "root_pid1", None, None,
        "exact_device_inode_owner_flags",
    ),
    Stage2ExecFdAuthorityRowV3(
        2, "stderr_diagnostic", "/dev/console_char_5:1",
        ("O_WRONLY", "O_NOCTTY", "O_NONBLOCK"),
        ("O_WRONLY", "O_NONBLOCK"), "non_CLOEXEC", "stage2_pid1",
        "one_line_diagnostics_only", "stage2_pid1", True, "separate_open",
        "character_device", (), None, "root_pid1", None, None,
        "exact_device_inode_owner_flags",
    ),
    Stage2ExecFdAuthorityRowV3(
        3, "handoff", "anonymous_sealed_spp-handoff-v3_memfd",
        ("MFD_CLOEXEC", "MFD_ALLOW_SEALING"), ("O_RDWR",),
        "clear_readback_before_exec_restore_readback_after_exec", "stage1",
        "consume_once_close_and_prove_original_inode_absence", "closed", True,
        "sealed_memfd", "one_use_handoff", (), 1048, "stage1_then_stage2", None,
        None, "exact_memfd_name_size_seals_offset_inode_flags",
    ),
    Stage2ExecFdAuthorityRowV3(
        4, "device_monitor", "sealed_uevent_device_monitor",
        ("SOCK_RAW", "SOCK_NONBLOCK", "SOCK_CLOEXEC"),
        ("O_RDWR", "O_NONBLOCK"),
        "clear_readback_before_exec_restore_readback_after_exec", "stage1",
        "retain_sealed_monitor", "stage2_pid1", True, "sealed_monitor",
        "NETLINK_KOBJECT_UEVENT", (), None, "kernel_sender_only",
        "sequence_and_overflow_closed", "CAP_NET_ADMIN",
        "exact_socket_inode_owner_flags_registration",
    ),
    Stage2ExecFdAuthorityRowV3(
        5, "broker_tpm", "/dev/tpmrm0_resource_manager_transfer",
        ("O_RDWR", "O_CLOEXEC"), ("O_RDWR",),
        "clear_readback_before_exec_restore_readback_after_exec", "stage1",
        "transfer_once_to_broker_fd4_close_pid1_copy_prove_absence",
        "attestation_broker", True, "tpm_resource_manager", "bounded_transfer",
        (), None, "sealed_registration", None, None,
        "exact_device_inode_owner_flags_registration",
    ),
    Stage2ExecFdAuthorityRowV3(
        6, "predicate5_trace", "package_selected_logical_trace_role", (), (),
        "clear_readback_before_exec_restore_readback_after_exec_after_binding",
        "stage1", "unissuable_until_exact_target_binding", "stage2_pid1", False,
        None, None, None, None, None, None, None, None,
    ),
)

_STAGE2_FD_CENSUS_STANDARD_V3: Final = (
    Stage2FdCensusEntryV3(
        0, "stdin", "stage2_pid1", ("FD_CLOEXEC_absent",), ("O_RDONLY",),
        "/dev/null_char_1:3", "boot_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        1, "stdout_evidence", "stage2_pid1", ("FD_CLOEXEC_absent",),
        ("O_WRONLY", "O_NONBLOCK"), "/dev/console_char_5:1:stdout_separate_ofd",
        "boot_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        2, "stderr_diagnostic", "stage2_pid1", ("FD_CLOEXEC_absent",),
        ("O_WRONLY", "O_NONBLOCK"), "/dev/console_char_5:1:stderr_separate_ofd",
        "boot_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        4, "device_monitor", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"), "sealed_uevent_device_monitor",
        "boot_generation_1:device_monitor", False,
    ),
)
_STAGE2_FD_CENSUS_BROKER_TPM_V3: Final = Stage2FdCensusEntryV3(
    5, "broker_tpm", "stage2_pid1", ("FD_CLOEXEC",), ("O_RDWR",),
    "/dev/tpmrm0_resource_manager_transfer", "boot_generation_1:tpm_registration",
    False,
)
_STAGE2_FD_CENSUS_TRACE_V3: Final = Stage2FdCensusEntryV3(
    6, "predicate5_trace", "stage2_pid1", (), (),
    "package_selected_logical_trace_role",
    "logical_generation_0:exact_target_binding_pending", True,
)
_STAGE2_FD_CENSUS_SUPERVISOR_V3: Final = (
    Stage2FdCensusEntryV3(
        7, "signalfd", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "anon_inode:signalfd:SIGCHLD,SIGTERM,SIGINT,SIGHUP,SIGQUIT",
        "controller_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        8, "timerfd", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"), "anon_inode:timerfd:CLOCK_MONOTONIC:5s",
        "controller_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        9, "epoll", "stage2_pid1", ("FD_CLOEXEC",), ("O_RDWR",),
        "anon_inode:eventpoll:sole_pid1_owner", "controller_generation_1", False,
    ),
)
_STAGE2_FD_CENSUS_SERVING_V3: Final = (
    Stage2FdCensusEntryV3(
        10, "listener", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "AF_INET:SOCK_STREAM:0.0.0.0:9443:backlog8",
        "controller_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        11, "gateway_control", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "AF_UNIX:SOCK_SEQPACKET:SO_PASSCRED:gateway_control_parent",
        "gateway_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        12, "readiness_broker", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "AF_UNIX:SOCK_SEQPACKET:SO_PASSCRED:readiness_broker_parent",
        "attestation_broker_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        13, "readiness_inference", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "AF_UNIX:SOCK_SEQPACKET:SO_PASSCRED:readiness_inference_parent",
        "inference_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        14, "readiness_asr", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDWR", "O_NONBLOCK"),
        "AF_UNIX:SOCK_SEQPACKET:SO_PASSCRED:readiness_asr_parent",
        "asr_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        15, "drain_broker_stdout", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:attestation_broker:stdout:read_end",
        "attestation_broker_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        16, "drain_broker_stderr", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:attestation_broker:stderr:read_end",
        "attestation_broker_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        17, "drain_inference_stdout", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:inference:stdout:read_end",
        "inference_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        18, "drain_inference_stderr", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:inference:stderr:read_end",
        "inference_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        19, "drain_asr_stdout", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:asr:stdout:read_end",
        "asr_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        20, "drain_asr_stderr", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:asr:stderr:read_end",
        "asr_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        21, "drain_gateway_stdout", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:gateway:stdout:read_end",
        "gateway_generation_1", False,
    ),
    Stage2FdCensusEntryV3(
        22, "drain_gateway_stderr", "stage2_pid1", ("FD_CLOEXEC",),
        ("O_RDONLY", "O_NONBLOCK"), "pipe:gateway:stderr:read_end",
        "gateway_generation_1", False,
    ),
)

_STAGE2_FD_CENSUS_ROWS_V3: Final = (
    Stage2FdCensusRowV3(
        "post_admission", "after_typed_admission_readback",
        (*_STAGE2_FD_CENSUS_STANDARD_V3, _STAGE2_FD_CENSUS_BROKER_TPM_V3,
         _STAGE2_FD_CENSUS_TRACE_V3),
        6, ("predicate5_trace",),
    ),
    Stage2FdCensusRowV3(
        "prelaunch", "after_signal_fd_supervisor_before_first_child_fork",
        (*_STAGE2_FD_CENSUS_STANDARD_V3, _STAGE2_FD_CENSUS_BROKER_TPM_V3,
         _STAGE2_FD_CENSUS_TRACE_V3, *_STAGE2_FD_CENSUS_SUPERVISOR_V3),
        9, ("predicate5_trace",),
    ),
    Stage2FdCensusRowV3(
        "steady_serving", "immediately_before_serving_authority_admission",
        (*_STAGE2_FD_CENSUS_STANDARD_V3, _STAGE2_FD_CENSUS_TRACE_V3,
         *_STAGE2_FD_CENSUS_SUPERVISOR_V3, *_STAGE2_FD_CENSUS_SERVING_V3),
        21, ("predicate5_trace",),
    ),
)

_STAGE2_SIGNAL_REAP_ROW_V3: Final = Stage2SignalReapRowV3(
    "pid1_signal_reap", "rt_sigprocmask:SIG_BLOCK:exact_mask", 1,
    "before_any_thread_or_child", _STAGE2_SIGNAL_MASK_V3,
    ("SIGPIPE",), (), "SIG_DFL",
    ("SA_NOCLDSTOP",), ("SA_NOCLDWAIT",),
    "SIG_DFL_no_behavior_changing_flags", ("SFD_NONBLOCK", "SFD_CLOEXEC"),
    _STAGE2_SIGNAL_MASK_V3, "stage2_pid1", "sole_pid1_epoll",
    ("async_handler", "second_signalfd", "sigwait", "sigwaitinfo",
     "sigtimedwait", "waitpid", "second_waitid", "other_SIGCHLD_consumer"),
    "P_ALL:0", ("WEXITED", "WNOHANG"),
    ("success_si_pid_zero_with_live_children", "error_ECHILD_with_no_children"),
    "fixed_records_until_EAGAIN", "full_signalfd_siginfo_record_per_read",
    ("SIGCHLD:CLD_EXITED", "SIGCHLD:CLD_KILLED", "SIGCHLD:CLD_DUMPED",
     "SIGTERM:SI_USER", "SIGTERM:SI_QUEUE", "SIGTERM:SI_TKILL",
     "SIGTERM:SI_KERNEL", "SIGINT:SI_USER", "SIGINT:SI_QUEUE",
     "SIGINT:SI_TKILL", "SIGINT:SI_KERNEL", "SIGHUP:SI_USER",
     "SIGHUP:SI_QUEUE", "SIGHUP:SI_TKILL", "SIGHUP:SI_KERNEL",
     "SIGQUIT:SI_USER", "SIGQUIT:SI_QUEUE", "SIGQUIT:SI_TKILL",
     "SIGQUIT:SI_KERNEL"),
    "short_unknown_or_mismatched_record_is_global_failure",
    "stop_or_continue_ssi_code_is_global_failure",
    "after_each_exit_SIGCHLD_and_immediately_before_each_blocking_epoll_wait",
    "nonzero_si_pid_consumed_once_matches_supervised_pid_start_time_role_generation",
    "after_each_complete_drain_exact_child_task_census_matches_empty_outcome_and_has_no_zombie",
    ("single_threaded_before_credentials_maps_exec", "close_inherited_signal_timer_epoll",
     "close_every_non_map_fd", "reset_SIGPIPE_and_all_catchable_to_SIG_DFL",
     "blocked_mask_empty", "pending_sets_empty", "install_only_exact_launch_fd_map"),
)

STAGE2_PID1_AUTHORITY_V3: Final = Stage2Pid1AuthorityV3(
    Stage2Pid1IdentityRowV3(
        "stage2_pid1", "/usr/lib/spp/conf_proc_spp_init.py",
        "/usr/bin/python3.10", _STAGE2_PID1_ARGV_V3, _FIXED_ROLE_ENVIRONMENT_V3,
        1, 0, 0, 0, (), "/", "/", "separate:/usr/bin/python3.10",
        "python3.10", "pid1_signal_reap",
    ),
    (
        Stage2ThreadCensusRowV3(
            "signal_setup", "immediately_before_signal_mask_first_install",
            ("1",), 1, 1, _STAGE2_PID1_PREMASK_PROCESS_STATE_V3,
            _STAGE2_PID1_PREMASK_TASK_STATE_V3,
        ),
        Stage2ThreadCensusRowV3(
            "capability_drop", "after_final_capability_drop_readback",
            ("1",), 1, 1, _STAGE2_PID1_STEADY_PROCESS_STATE_V3,
            _STAGE2_PID1_STEADY_TASK_STATE_V3,
        ),
        Stage2ThreadCensusRowV3(
            "launch", "immediately_before_first_child_fork",
            ("1",), 1, 1, _STAGE2_PID1_INITIAL_PROCESS_STATE_V3,
            _STAGE2_PID1_INITIAL_TASK_STATE_V3,
        ),
        Stage2ThreadCensusRowV3(
            "serving", "immediately_before_serving_authority_admission",
            ("1",), 1, 1, _STAGE2_PID1_STEADY_PROCESS_STATE_V3,
            _STAGE2_PID1_STEADY_TASK_STATE_V3,
        ),
    ),
    "stage2_spawn_child_v3:fork",
    ("_thread", "threading", "pthread", "clone3", "clone:CLONE_THREAD"),
    "exact_target_continuous_clone_event_trace_stage2_entry_through_serving",
    (
        Stage2CapabilityPhaseRowV3(
            "stage2_admitted", "after_typed_admission_readback",
            _STAGE2_INITIAL_CAPABILITIES_V3, _STAGE2_INITIAL_CAPABILITIES_V3,
            (), (), _STAGE2_INITIAL_CAPABILITIES_V3, 0,
        ),
        Stage2CapabilityPhaseRowV3(
            "launch_supervision_ready",
            "after_signal_fd_supervisor_immediately_before_first_fork",
            _STAGE2_INITIAL_CAPABILITIES_V3, _STAGE2_INITIAL_CAPABILITIES_V3,
            (), (), _STAGE2_INITIAL_CAPABILITIES_V3, 0,
        ),
        Stage2CapabilityPhaseRowV3(
            "serving_steady",
            "after_DHCP_socket_identity_absence_and_ordered_drop_readback",
            _STAGE2_STEADY_CAPABILITIES_V3, _STAGE2_STEADY_CAPABILITIES_V3,
            (), (), _STAGE2_STEADY_CAPABILITIES_V3, 0,
        ),
    ),
    ("require_original_DHCP_socket_identity_absent",
     "remove_CAP_NET_BIND_SERVICE_effective_permitted",
     "PR_CAPBSET_DROP_CAP_NET_BIND_SERVICE", "PR_CAPBSET_DROP_CAP_SETPCAP",
     "remove_CAP_SETPCAP_effective_permitted",
     "readback_all_capability_surfaces_and_prove_both_non_regainable"),
    _STAGE2_EXEC_FD_AUTHORITY_ROWS_V3,
    ("kcmp:0:1=positive", "kcmp:0:2=positive", "kcmp:1:2=positive"),
    _STAGE2_FD_CENSUS_ROWS_V3,
    _STAGE2_SIGNAL_REAP_ROW_V3,
    (
        Stage2SignalOutcomeRowV3(
            "SIGTERM", "shutdown_sigterm", "current_controller_epoch",
            "global_fail_stop",
        ),
        Stage2SignalOutcomeRowV3(
            "SIGINT", "shutdown_sigint", "current_controller_epoch",
            "global_fail_stop",
        ),
        Stage2SignalOutcomeRowV3(
            "SIGHUP", "shutdown_sighup", "current_controller_epoch",
            "global_fail_stop",
        ),
        Stage2SignalOutcomeRowV3(
            "SIGQUIT", "shutdown_sigquit", "current_controller_epoch",
            "global_fail_stop",
        ),
    ),
    ControllerTerminalEpochV3(
        "controller_terminal_epoch",
        ("shutdown_signal_outcome", "unknown_child_exit", "long_lived_role_exit"),
        "stage2_pid1_sole_event_loop_state",
        ("latch_terminal", "increment_nonzero_controller_epoch_once",
         "invalidate_prior_epoch_readiness_candidates_and_completions",
         "close_serving_issuance"),
        "duplicate_or_mixed_shutdown_observes_existing_terminal_epoch_only",
        "signalfd_drain_and_child_reap_before_any_readiness_record",
        "same_live_epoch_and_terminal_false_compare_and_set",
        "only_current_authorized_collector_identity_status_enters_typed_finish_or_abort",
    ),
    Stage2LogicalTraceAuthorityRowV3(
        "predicate5_trace", 6, True, False, None, None, None, None, None, None,
        None, None,
    ),
)


STAGE2_CONTROLLER_ROW_V3: Final = Stage2ControllerRowV3(
    "/usr/lib/spp/conf_proc_spp_init.py", 4604,
    "32b7c8f5b6772f52433adcca11051ad1e883bb59aa4f7c66116e43a379bd1dd3",
    "/usr/bin/python3.10",
    _STAGE2_PID1_ARGV_V3,
    _FIXED_ROLE_ENVIRONMENT_V3, 0, 0, (), "/", "/", _ROLE_NAMESPACES_V3,
    (
        Stage2FdRowV3(0, "stdin", "non_CLOEXEC", "retain_standard", "stage2_pid1"),
        Stage2FdRowV3(1, "stdout_evidence", "non_CLOEXEC", "framed_evidence_only", "stage2_pid1"),
        Stage2FdRowV3(2, "stderr_diagnostic", "non_CLOEXEC", "one_line_diagnostics_only", "stage2_pid1"),
        Stage2FdRowV3(3, "sealed_handoff_memfd", "clear_and_readback_immediately_before_same_exec", "consume_once_close_and_prove_absence_before_post_exec_effect", "closed"),
        Stage2FdRowV3(4, "sealed_device_monitor", "clear_and_readback_immediately_before_same_exec", "set_and_readback_CLOEXEC_before_other_post_exec_effect", "stage2_pid1"),
        Stage2FdRowV3(5, "bounded_broker_TPM_transfer", "clear_and_readback_immediately_before_same_exec", "prove_identity_set_and_readback_CLOEXEC_then_transfer_once_to_broker_fd4_close_pid1_copy_prove_absence", "attestation_broker"),
        Stage2FdRowV3(6, "predicate5_trace", "clear_and_readback_only_after_exact_target_binding", "unissuable_until_exact_target_binding", "stage2_pid1"),
    ),
    (
        "only_fds_3_4_5_6_clear_FD_CLOEXEC_for_stage2_exec_after_fd6_binding",
        "fd3_and_fd4_created_sealed_CLOEXEC_before_stage2_exec",
        "fd3_consumed_once_then_closed_and_inode_fd_absence_proven",
        "fd4_FD_CLOEXEC_restored_and_read_back_before_other_post_exec_effect",
        "fd5_opened_only_after_PCR15_readback_and_boot_transport_close_with_O_RDWR_O_CLOEXEC",
        "fd5_matches_sealed_TPM_resource_manager_registration_boot_epoch_device_identity",
        "stage2_issues_no_TPM_command_and_transfers_fd5_once_to_broker_fd4",
        "broker_sets_and_reads_back_FD_CLOEXEC_on_fd4_after_exec",
        "fd6_logical_role_is_nonissuable_with_null_physical_fields_until_exact_target_binding",
    ),
    (
        ("hostname", "services.solstone.app"), ("resolver", "168.63.129.16:53"), ("tcp_peer_port", "443"),
        ("query", "one_fresh_nonzero_u16_RD_only_QDCOUNT_1_lowercase_A_IN"),
        ("response", "exact_resolver_question_flags_counts_A_IN_4_byte_RDATA_no_trailing"),
        ("ttl_seconds", "1..3600"), ("selection", "lowest_unsigned_public_unicast_ipv4"),
        ("tcp_retry", "at_most_one_after_TC_only_same_resolver_fresh_transaction_id"),
    ),
    (
        ("family", "inet"), ("table", "spp_filter"), ("chain", "output"),
        ("chain_shape", "type_filter_output_hook_priority_0_policy_drop"),
        ("rule", "selected_ipv4_TCP_443_sealed_NIC_ifindex_root_UID_conntrack_new_unique_handle"),
        ("lifecycle", "atomic_apply_readback_remove_absence"),
        ("clean_reject", "policy_apply_rejected_closed_only_before_mutation_exact_base_dump_rule_absence"),
    ),
    ("none", "connecting", "fd_sent", "acked", "rejected"),
    _STAGE2_INITIAL_CAPABILITIES_V3,
    _STAGE2_STEADY_CAPABILITIES_V3,
    STAGE2_PID1_AUTHORITY_V3,
)


@dataclass(frozen=True)
class ResourceActionRowV3:
    ordinal: int
    name: str


RESOURCE_ACTION_ROWS_V3: Final = (
    ResourceActionRowV3(1, "session_acquire"),
    ResourceActionRowV3(2, "collector_acquire"),
    ResourceActionRowV3(3, "collector_finish"),
    ResourceActionRowV3(4, "collector_abort"),
    ResourceActionRowV3(5, "request_acquire"),
    ResourceActionRowV3(6, "work_begin"),
    ResourceActionRowV3(7, "work_finish"),
    ResourceActionRowV3(8, "request_release"),
    ResourceActionRowV3(9, "session_release"),
    ResourceActionRowV3(10, "global_revoke"),
)
LISTEN_BACKLOG_V3: Final = 8
SOMAXCONN_MINIMUM_V3: Final = 8
MAX_LIVE_SESSIONS_V3: Final = 4
COLLECTOR_OPERATION_PERMITS_V3: Final = 1
COLLECTOR_OPERATION_BOUND_SECONDS_V3: Final = 180
COLLECTOR_OUTPUT_CAPACITY_BYTES_V3: Final = 8388608
ROUTE_WORK_PERMITS_TOTAL_V3: Final = 2
STREAM_BUFFER_BYTES_V3: Final = 2097152
AGGREGATE_BUFFER_BYTES_V3: Final = 4194304
REQUEST_HEAD_CAPACITY_BYTES_V3: Final = 32768
RELAY_COPY_CHUNK_BYTES_V3: Final = 65536


class ServingWireMessageTypeV3(IntEnum):
    SESSION_FD = 1
    COLLECTOR_REQUEST = 2
    COLLECTOR_RESPONSE = 3
    COLLECTOR_ACK_VALID = 4
    COLLECTOR_ACK_INVALID = 5
    COLLECTOR_CANCEL = 6
    REQUEST_ACQUIRE = 7
    REQUEST_ADMIT = 8
    REQUEST_REJECT = 9
    WORK_BEGIN = 10
    WORK_BEGUN = 11
    WORK_FINISH = 12
    WORK_FINISHED = 13
    REQUEST_RELEASE = 14
    REQUEST_RELEASED = 15
    SESSION_RELEASE = 16
    SESSION_RELEASED = 17
    PRE_REQUEST_REJECTED = 18
    GLOBAL_FAULT = 19
    CHUNK_ACK = 20
    SESSION_FD_ACK = 21
    GATEWAY_READINESS_PROBE = 22
    GATEWAY_READINESS_RESULT = 23


WIRE_MESSAGE_TYPE_ROWS_V3: Final = tuple(
    (message_type.value, message_type.name)
    for message_type in ServingWireMessageTypeV3
)


@dataclass(frozen=True)
class WirePayloadFieldV3:
    name: str
    kind: str
    byte_width: int | None
    constraint: str


@dataclass(frozen=True)
class WirePayloadVariantV3:
    condition: str
    fields: tuple[WirePayloadFieldV3, ...]


@dataclass(frozen=True)
class WireMessageAuthorityRowV3:
    type_id: int
    name: str
    direction: str
    prerequisite: str
    payload_shape: tuple[WirePayloadFieldV3, ...]
    payload_variants: tuple[WirePayloadVariantV3, ...]
    fd_rule: str
    session_coordinate_rule: str
    sequence_rule: str
    header_rule: str


@dataclass(frozen=True)
class WireEnumRowV3:
    domain: str
    value: int
    name: str


@dataclass(frozen=True)
class WireConditionalShapeRowV3:
    name: str
    rule: str


WIRE_HEADER_FIELDS_V3: Final = (
    WirePayloadFieldV3("magic", "bytes", 8, "SPPIPC3\\0"),
    WirePayloadFieldV3("version", "u16_be", 2, "3"),
    WirePayloadFieldV3("type", "u16_be", 2, "declared_type_id"),
    WirePayloadFieldV3("flags", "u16_be", 2, "START=1_END=2_HAS_FD=4_only"),
    WirePayloadFieldV3("reserved", "zero", 2, "all_zero"),
    WirePayloadFieldV3("global_sequence", "u32_be", 4, "per_direction_exact_previous_plus_1_from_1"),
    WirePayloadFieldV3("chunk_index", "u32_be", 4, "row_chunk_rule"),
    WirePayloadFieldV3("chunk_count", "u32_be", 4, "row_chunk_rule"),
    WirePayloadFieldV3("chunk_length", "u32_be", 4, "exact_payload_chunk_length"),
    WirePayloadFieldV3("total_length", "u64_be", 8, "exact_total_payload_length"),
    WirePayloadFieldV3("session_coordinate", "bytes", 32, "row_session_coordinate_rule"),
)
WIRE_HEADER_BYTES_V3: Final = 72
WIRE_SEQUENCE_RULE_V3: Final = "each_direction_starts_1_exact_previous_plus_1_no_gap_duplicate_or_wrap_0xffffffff_exhaustion_fails"
WIRE_HAS_FD_TYPE_IDS_V3: Final = (1, 25)
WIRE_SESSION_COORDINATE_RULES_V3: Final = (
    WireConditionalShapeRowV3("types_1_18_21_24_27", "exact_nonzero_session_token"),
    WireConditionalShapeRowV3("type_20", "copies_acknowledged_message_session_token"),
    WireConditionalShapeRowV3("types_22_23", "32_zero_bytes"),
    WireConditionalShapeRowV3("type_19", "matching_nonzero_token_and_cycle_for_session_fault_otherwise_both_zero"),
)


def _field(name: str, kind: str, width: int | None, constraint: str = "exact") -> WirePayloadFieldV3:
    return WirePayloadFieldV3(name, kind, width, constraint)


def _row(
    type_id: int, name: str, direction: str, prerequisite: str,
    fields: tuple[WirePayloadFieldV3, ...], *, fd_rule: str = "no_fd",
    variants: tuple[WirePayloadVariantV3, ...] = (), session: str = "exact_nonzero_session_token",
) -> WireMessageAuthorityRowV3:
    return WireMessageAuthorityRowV3(type_id, name, direction, prerequisite, fields, variants, fd_rule, session, WIRE_SEQUENCE_RULE_V3, "exact_72_byte_SPPIPC3_header")


WIRE_ROUTE_ENUM_ROWS_V3: Final = (WireEnumRowV3("route", 1, "inference"), WireEnumRowV3("route", 2, "asr"))
WIRE_COLLECTOR_GENERATION_ENUM_ROWS_V3: Final = (WireEnumRowV3("collector_generation", 1, "certificate"), WireEnumRowV3("collector_generation", 2, "exporter"))
WIRE_COLLECTOR_RESULT_ENUM_ROWS_V3: Final = (
    WireEnumRowV3("collector_result", 1, "success"), WireEnumRowV3("collector_result", 2, "acquire_rejected"), WireEnumRowV3("collector_result", 3, "aborted"),
)
WIRE_COLLECTOR_ABORT_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("collector_abort_reason", value, name) for value, name in (
    (1, "nonzero_exit"), (2, "timeout"), (3, "stdout_overflow"), (4, "stderr_overflow"), (5, "malformed"), (6, "identity"), (7, "client_close"), (8, "cancelled"),
))
WIRE_INVALID_COLLECTOR_ACK_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("invalid_collector_ack_reason", value, name) for value, name in ((1, "shape"), (2, "binding"), (3, "encoding"), (4, "identity")))
WIRE_INVALID_COLLECTOR_ACK_ABORT_MAPPING_V3: Final = ((1, 5), (2, 6), (3, 5), (4, 6))
WIRE_COLLECTOR_CANCEL_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("collector_cancel_reason", value, name) for value, name in ((1, "timeout"), (2, "client_close"), (3, "shutdown")))
WIRE_REQUEST_REJECT_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("request_reject_reason", value, name) for value, name in ((1, "route_slot_saturated"), (2, "duplicate_request")))
WIRE_WORK_FINISH_OUTCOME_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("work_finish_outcome", value, name) for value, name in ((1, "ordinary"), (2, "upstream_return"), (3, "upstream_throw"), (4, "upstream_timeout"), (5, "client_close")))
WIRE_REQUEST_RELEASE_STATE_ENUM_ROWS_V3: Final = (WireEnumRowV3("request_release_state", 1, "work_finished"), WireEnumRowV3("request_release_state", 2, "audio_413"))
WIRE_SESSION_RELEASE_HELD_BITS_V3: Final = ((1, "request"), (2, "route_work"), (4, "buffer"))
WIRE_SESSION_RELEASE_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("session_release_reason", value, name) for value, name in (
    (1, "normal_client_close"), (2, "preface_failed"), (3, "certificate_failed"), (4, "tls_failed"), (5, "exporter_request_failed"), (6, "exporter_collector_failed"), (7, "proof_write_failed"), (8, "parser_rejected"), (9, "saturation"), (10, "credential_failed"), (11, "dns_failed"), (12, "entitlement_tls_failed"), (13, "authorization_denied"), (14, "upstream_failed"), (15, "hard_audio"),
))
WIRE_PRE_REQUEST_REJECT_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("pre_request_reject_reason", value, name) for value, name in ((1, "malformed"), (2, "head_oversize"), (3, "chunked"), (4, "first_byte_idle"), (5, "head_deadline"), (6, "client_close"), (7, "return"), (8, "throw")))
WIRE_GLOBAL_FAULT_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("global_fault_reason", value, name) for value, name in ((1, "reducer_identity"), (2, "process_identity"), (3, "socket_identity"), (4, "readiness"), (5, "policy_readback"), (6, "control_protocol")))
WIRE_ENTITLEMENT_CONNECT_REJECT_REASON_ENUM_ROWS_V3: Final = tuple(WireEnumRowV3("entitlement_connect_reject_reason", value, name) for value, name in ((1, "saturated"), (2, "dns_timeout"), (3, "dns_malformed"), (4, "no_admissible_public_a"), (5, "connect_timeout"), (6, "connect_failed"), (7, "policy_apply_rejected_closed")))
WIRE_CONDITIONAL_SHAPE_ROWS_V3: Final = (
    WireConditionalShapeRowV3("collector_success", "reason_zero_nonzero_child_pid_wait_status_zero_exact_stdout_sha256_canonical_nonempty_json"),
    WireConditionalShapeRowV3("collector_acquire_rejected", "reason_saturated_zero_child_pid_wait_status_stdout_sha256_no_tail"),
    WireConditionalShapeRowV3("collector_aborted", "reason_1_to_8_reaped_child_fields_zero_only_if_no_child_no_tail"),
    WireConditionalShapeRowV3("session_release_slots", "absent_32_zero_bytes_present_exact_live_ledger"),
    WireConditionalShapeRowV3("entitlement_connect_reject", "reasons_1_2_3_4_7_zero_dns_fields_reasons_5_6_exact_nonzero_dns_fields"),
    WireConditionalShapeRowV3("gateway_readiness_result", "control_ready_1_worker_count_0_to_4_equals_pid1_live_session_ledger"),
)


WIRE_MESSAGE_AUTHORITY_ROWS_V3: Final = (
    _row(1, "SESSION_FD", "PID1->gateway", "after_accept_readback", (_field("epoch", "u64_be", 8), _field("family", "u16_be", 2, "AF_INET"), _field("local_ipv4", "bytes", 4), _field("local_port", "u16_be", 2), _field("peer_ipv4", "bytes", 4), _field("peer_port", "u16_be", 2), _field("SO_COOKIE", "u64_be", 8)), fd_rule="one_fd"),
    _row(2, "COLLECTOR_REQUEST", "gateway->PID1", "for_exact_next_generation", (_field("generation", "u8", 1, "collector_generation"), _field("reserved", "zero", 3), _field("canonical_request_json", "canonical_json", None))),
    _row(3, "COLLECTOR_RESPONSE", "PID1->gateway", "after_typed_child_boundary", (_field("generation", "u8", 1), _field("result", "u8", 1, "collector_result"), _field("reason", "u16_be", 2, "conditional"), _field("child_pid", "u32_be", 4, "conditional"), _field("wait_status", "u32_be", 4, "conditional"), _field("stdout_sha256", "bytes", 32, "conditional"), _field("conditional_json", "canonical_json", None, "success_only")), variants=(WirePayloadVariantV3("success_acquire_rejected_aborted_exact_shapes", ()),)),
    _row(4, "COLLECTOR_ACK_VALID", "gateway->PID1", "after_semantic_success_validation", (_field("generation", "u8", 1), _field("reserved", "zero", 3), _field("child_pid", "u32_be", 4), _field("wait_status", "u32_be", 4), _field("stdout_sha256", "bytes", 32))),
    _row(5, "COLLECTOR_ACK_INVALID", "gateway->PID1", "after_semantic_rejection", (_field("generation", "u8", 1), _field("reserved", "zero", 3), _field("child_pid", "u32_be", 4), _field("wait_status", "u32_be", 4), _field("stdout_sha256", "bytes", 32), _field("reason", "u16_be", 2, "1..4"))),
    _row(6, "COLLECTOR_CANCEL", "gateway->PID1", "while_child_may_run", (_field("generation", "u8", 1), _field("reason", "u8", 1, "collector_cancel_reason"), _field("reserved", "zero", 2))),
    _row(7, "REQUEST_ACQUIRE", "gateway->PID1", "after_parse_before_local_request_start", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reserved", "zero", 7), _field("gateway_reducer_token", "bytes", 32))),
    _row(8, "REQUEST_ADMIT", "PID1->gateway", "after_atomic_acquire", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reserved", "zero", 3), _field("stream_buffer_bytes", "u32_be", 4, "2097152"), _field("request_token", "bytes", 32), _field("route_token", "bytes", 32), _field("buffer_token", "bytes", 32))),
    _row(9, "REQUEST_REJECT", "PID1->gateway", "with_no_permit", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reason", "u8", 1, "request_reject_reason"), _field("reserved", "zero", 6))),
    _row(10, "WORK_BEGIN", "gateway->PID1", "immediately_before_local_upstream_open", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reserved", "zero", 7), _field("request_token", "bytes", 32), _field("route_token", "bytes", 32))),
    _row(11, "WORK_BEGUN", "PID1->gateway", "after_queued_to_executing", (_field("payload", "echo", None, "byte_identical_type_10_payload"),)),
    _row(12, "WORK_FINISH", "gateway->PID1", "after_begun_work_ends", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("outcome", "u8", 1, "work_finish_outcome"), _field("reserved", "zero", 6), _field("request_token", "bytes", 32), _field("route_token", "bytes", 32))),
    _row(13, "WORK_FINISHED", "PID1->gateway", "after_executing_to_finished", (_field("payload", "echo", None, "byte_identical_type_12_payload"),)),
    _row(14, "REQUEST_RELEASE", "gateway->PID1", "after_work_acked_egress_fd_close_or_413_no_egress", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("state", "u8", 1, "request_release_state"), _field("reserved", "zero", 6), _field("request_token", "bytes", 32), _field("route_token", "bytes", 32), _field("buffer_token", "bytes", 32))),
    _row(15, "REQUEST_RELEASED", "PID1->gateway", "before_local_request_close", (_field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reserved", "zero", 7), _field("request_token", "bytes", 32))),
    _row(16, "SESSION_RELEASE", "gateway->PID1", "after_collector_terminal_and_egress_terminal", (_field("cycle", "u64_be", 8), _field("held_bitmap", "u16_be", 2, "request=1_route_work=2_buffer=4"), _field("reason", "u16_be", 2, "session_release_reason"), _field("reserved", "zero", 4), _field("request_slot", "bytes", 32, "conditional_live_ledger"), _field("route_slot", "bytes", 32, "conditional_live_ledger"), _field("buffer_slot", "bytes", 32, "conditional_live_ledger"))),
    _row(17, "SESSION_RELEASED", "PID1->gateway", "after_exact_unwind", (_field("cycle", "u64_be", 8), _field("prior_bitmap", "u16_be", 2), _field("prior_reason", "u16_be", 2), _field("reserved", "zero", 4))),
    _row(18, "PRE_REQUEST_REJECTED", "gateway->PID1", "before_request_acquire", (_field("next_cycle", "u64_be", 8), _field("reason", "u16_be", 2, "pre_request_reject_reason"), _field("reserved", "zero", 6))),
    _row(19, "GLOBAL_FAULT", "gateway->PID1", "for_listed_global_local_fault", (_field("cycle", "u64_be", 8, "conditional"), _field("reason", "u16_be", 2, "global_fault_reason"), _field("reserved", "zero", 6), _field("gateway_reducer_token", "bytes", 32)), session="conditional_matching_token_and_cycle_or_zero"),
    _row(20, "CHUNK_ACK", "current_receiver->sender", "for_prior_chunk", (_field("sequence", "u32_be", 4), _field("chunk_index", "u32_be", 4), _field("cumulative_bytes", "u64_be", 8), _field("rolling_sha256", "bytes", 32)), session="copies_acknowledged_message_session_token"),
    _row(21, "SESSION_FD_ACK", "gateway->PID1", "after_exact_client_fd_readback", (_field("epoch", "u64_be", 8), _field("SO_COOKIE", "u64_be", 8), _field("gateway_reducer_token", "bytes", 32))),
    _row(22, "GATEWAY_READINESS_PROBE", "PID1->gateway", "at_mandatory_census", (_field("census_generation", "u64_be", 8), _field("absolute_monotonic_deadline_ns", "u64_be", 8)), session="32_zero_bytes"),
    _row(23, "GATEWAY_READINESS_RESULT", "gateway->PID1", "before_deadline", (_field("generation", "u64_be", 8), _field("pid", "u32_be", 4, "nonzero"), _field("worker_count", "u16_be", 2, "0..4_equals_live_session_ledger"), _field("control_ready_flag", "u16_be", 2, "1"), _field("executable_sha256", "bytes", 32), _field("control_cookie", "u64_be", 8)), session="32_zero_bytes"),
    _row(24, "ENTITLEMENT_CONNECT_REQUEST", "gateway->PID1", "after_admit_local_request_credential_readbacks_pending_DNS_effect", (_field("epoch", "u64_be", 8), _field("cycle", "u64_be", 8), _field("route", "u8", 1, "route"), _field("reserved", "zero", 7), _field("request_token", "bytes", 32), _field("gateway_reducer_token", "bytes", 32))),
    _row(25, "ENTITLEMENT_CONNECT_FD", "PID1->gateway", "after_exact_DNS_rule_connect_readback_rule_absence", (_field("type_24_prefix", "echo", None, "byte_identical_type_24_prefix"), _field("ttl", "u32_be", 4), _field("reserved0", "zero", 4), _field("dns_time_ns", "u64_be", 8), _field("family", "u16_be", 2, "AF_INET"), _field("socket_type", "u16_be", 2, "SOCK_STREAM"), _field("peer_ipv4", "bytes", 4), _field("peer_port", "u16_be", 2, "443"), _field("local_ipv4", "bytes", 4), _field("local_port", "u16_be", 2), _field("SO_ERROR", "u32_be", 4, "0"), _field("reserved1", "zero", 4), _field("SO_COOKIE", "u64_be", 8), _field("egress_token", "bytes", 32)), fd_rule="one_fd_then_PID1_close_and_absence"),
    _row(26, "ENTITLEMENT_CONNECT_REJECT", "PID1->gateway", "only_with_proven_rule_and_fd_absence", (_field("type_24_prefix", "echo", None, "byte_identical_type_24_prefix"), _field("reason", "u16_be", 2, "entitlement_connect_reject_reason"), _field("reserved", "zero", 2), _field("ttl", "u32_be", 4, "conditional"), _field("dns_time_ns", "u64_be", 8, "conditional"), _field("selected_ipv4", "bytes", 4, "conditional"), _field("reserved2", "zero", 4))),
    _row(27, "ENTITLEMENT_CONNECT_ACK", "gateway->PID1", "after_MSG_CMSG_CLOEXEC_and_full_fd_readback", (_field("payload", "echo", None, "byte_identical_type_25_payload"),)),
)
