#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Stable public failures for SPP diagnostic runtime builder operations."""

from __future__ import annotations

from typing import Final


CP_SPP_DIAG_RUNTIME_BUILD_CONSOLE: Final = "CP_SPP_DIAG_RUNTIME_BUILD_CONSOLE"
CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_ARG: Final = "CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_ARG"
CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_DUPLICATE: Final = "CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_DUPLICATE"
CP_SPP_DIAG_RUNTIME_BUILD_DEST_PATH: Final = "CP_SPP_DIAG_RUNTIME_BUILD_DEST_PATH"
CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_DECLARATION: Final = "CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_DECLARATION"
CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_EXISTS: Final = "CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_EXISTS"
CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_STAT: Final = "CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_STAT"
CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_CONTENT: Final = "CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_CONTENT"
CP_SPP_DIAG_RUNTIME_BUILD_STAGING: Final = "CP_SPP_DIAG_RUNTIME_BUILD_STAGING"
CP_SPP_DIAG_RUNTIME_BUILD_REOPEN: Final = "CP_SPP_DIAG_RUNTIME_BUILD_REOPEN"
CP_SPP_DIAG_RUNTIME_BUILD_CLOSURE: Final = "CP_SPP_DIAG_RUNTIME_BUILD_CLOSURE"
CP_SPP_DIAG_RUNTIME_BUILD_INTERNAL_NODE: Final = "CP_SPP_DIAG_RUNTIME_BUILD_INTERNAL_NODE"
CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_CHANGED: Final = "CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_CHANGED"
CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_MEMBERS: Final = "CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_MEMBERS"
CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_SEAM: Final = "CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_SEAM"
CP_SPP_DIAG_RUNTIME_BUILD_COMMAND_LINE: Final = "CP_SPP_DIAG_RUNTIME_BUILD_COMMAND_LINE"

ALL_SPP_DIAG_RUNTIME_BUILD_REASONS: Final = frozenset(
    {
        CP_SPP_DIAG_RUNTIME_BUILD_CONSOLE,
        CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_ARG,
        CP_SPP_DIAG_RUNTIME_BUILD_RESERVED_DUPLICATE,
        CP_SPP_DIAG_RUNTIME_BUILD_DEST_PATH,
        CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_DECLARATION,
        CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_EXISTS,
        CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_STAT,
        CP_SPP_DIAG_RUNTIME_BUILD_SOURCE_CONTENT,
        CP_SPP_DIAG_RUNTIME_BUILD_STAGING,
        CP_SPP_DIAG_RUNTIME_BUILD_REOPEN,
        CP_SPP_DIAG_RUNTIME_BUILD_CLOSURE,
        CP_SPP_DIAG_RUNTIME_BUILD_INTERNAL_NODE,
        CP_SPP_DIAG_RUNTIME_BUILD_DESTINATION_CHANGED,
        CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_MEMBERS,
        CP_SPP_DIAG_RUNTIME_BUILD_IMAGE_SEAM,
        CP_SPP_DIAG_RUNTIME_BUILD_COMMAND_LINE,
    }
)


class SppDiagRuntimeBuildError(RuntimeError):
    """One stable public runtime-builder reason code."""

    def __init__(self, reason_code: str) -> None:
        if reason_code not in ALL_SPP_DIAG_RUNTIME_BUILD_REASONS:
            raise ValueError("unknown SPP diagnostic runtime-builder reason")
        self.reason_code = reason_code
        super().__init__(reason_code)
