#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Stable reason codes and common failure type for conf-proc artifacts."""

from __future__ import annotations

from typing import Final


CP_TOOL_MISSING: Final = "CP_TOOL_MISSING"
CP_TOOL_PATH_ESCAPE: Final = "CP_TOOL_PATH_ESCAPE"
CP_TOOL_DIGEST_MISMATCH: Final = "CP_TOOL_DIGEST_MISMATCH"
CP_TOOL_INVOCATION_FAILED: Final = "CP_TOOL_INVOCATION_FAILED"

CP_HERMETIC_UNLISTED_READ: Final = "CP_HERMETIC_UNLISTED_READ"
CP_HERMETIC_UNLISTED_WRITE: Final = "CP_HERMETIC_UNLISTED_WRITE"
CP_HERMETIC_UNLISTED_SUBPROCESS: Final = "CP_HERMETIC_UNLISTED_SUBPROCESS"
CP_HERMETIC_ENV: Final = "CP_HERMETIC_ENV"
CP_HERMETIC_CLOCK: Final = "CP_HERMETIC_CLOCK"
CP_HERMETIC_PATH_ESCAPE: Final = "CP_HERMETIC_PATH_ESCAPE"
CP_HERMETIC_NETWORK: Final = "CP_HERMETIC_NETWORK"

CP_JSON_INVALID_UTF8: Final = "CP_JSON_INVALID_UTF8"
CP_JSON_INVALID: Final = "CP_JSON_INVALID"
CP_JSON_NONCANONICAL: Final = "CP_JSON_NONCANONICAL"
CP_JSON_DUPLICATE_KEY: Final = "CP_JSON_DUPLICATE_KEY"
CP_JSON_UNSUPPORTED_NUMBER: Final = "CP_JSON_UNSUPPORTED_NUMBER"
CP_JSON_UNSUPPORTED_TYPE: Final = "CP_JSON_UNSUPPORTED_TYPE"

CP_LOCK_SCHEMA: Final = "CP_LOCK_SCHEMA"
CP_LOCK_DUPLICATE_ID: Final = "CP_LOCK_DUPLICATE_ID"
CP_LOCK_ROLE: Final = "CP_LOCK_ROLE"
CP_LOCK_INPUT_MISSING: Final = "CP_LOCK_INPUT_MISSING"
CP_LOCK_INPUT_PATH_ESCAPE: Final = "CP_LOCK_INPUT_PATH_ESCAPE"
CP_LOCK_DIGEST_MISMATCH: Final = "CP_LOCK_DIGEST_MISMATCH"
CP_LOCK_SIZE_MISMATCH: Final = "CP_LOCK_SIZE_MISMATCH"
CP_LOCK_PROVENANCE: Final = "CP_LOCK_PROVENANCE"
CP_LOCK_BASE_IMAGE_RECORD: Final = "CP_LOCK_BASE_IMAGE_RECORD"

CP_POLICY_SCHEMA: Final = "CP_POLICY_SCHEMA"
CP_POLICY_DUPLICATE: Final = "CP_POLICY_DUPLICATE"
CP_POLICY_TREE_RULE: Final = "CP_POLICY_TREE_RULE"
CP_POLICY_UNSUPPORTED_ACTIVATION: Final = "CP_POLICY_UNSUPPORTED_ACTIVATION"
CP_POLICY_GRAPH_MISMATCH: Final = "CP_POLICY_GRAPH_MISMATCH"
CP_POLICY_FORBIDDEN_NETWORK: Final = "CP_POLICY_FORBIDDEN_NETWORK"
CP_POLICY_CAPABILITY: Final = "CP_POLICY_CAPABILITY"

CP_TREE_MISSING: Final = "CP_TREE_MISSING"
CP_TREE_UNEXPECTED: Final = "CP_TREE_UNEXPECTED"
CP_TREE_NODE_TYPE: Final = "CP_TREE_NODE_TYPE"
CP_TREE_METADATA: Final = "CP_TREE_METADATA"
CP_TREE_XATTR: Final = "CP_TREE_XATTR"
CP_TREE_ACL: Final = "CP_TREE_ACL"
CP_TREE_SYMLINK: Final = "CP_TREE_SYMLINK"
CP_TREE_UNSUPPORTED_NODE: Final = "CP_TREE_UNSUPPORTED_NODE"
CP_TREE_SOURCE_BINDING: Final = "CP_TREE_SOURCE_BINDING"

CP_SQUASHFS_BUILD: Final = "CP_SQUASHFS_BUILD"
CP_SQUASHFS_EXTRACT: Final = "CP_SQUASHFS_EXTRACT"
CP_VERITY_FORMAT: Final = "CP_VERITY_FORMAT"
CP_VERITY_VERIFY: Final = "CP_VERITY_VERIFY"
CP_VERITY_GEOMETRY: Final = "CP_VERITY_GEOMETRY"
CP_VERITY_ROOT_MISMATCH: Final = "CP_VERITY_ROOT_MISMATCH"
CP_IMAGE_DIGEST_MISMATCH: Final = "CP_IMAGE_DIGEST_MISMATCH"

CP_MANIFEST_SCHEMA: Final = "CP_MANIFEST_SCHEMA"
CP_MANIFEST_FORBIDDEN_FIELD: Final = "CP_MANIFEST_FORBIDDEN_FIELD"
CP_MANIFEST_DIFF: Final = "CP_MANIFEST_DIFF"
CP_SBOM_SCHEMA: Final = "CP_SBOM_SCHEMA"
CP_SBOM_DIFF: Final = "CP_SBOM_DIFF"
CP_SBOM_MAPPING: Final = "CP_SBOM_MAPPING"

CP_RUNTIME_CLOSURE_SCHEMA: Final = "CP_RUNTIME_CLOSURE_SCHEMA"
CP_VERITY_RULES_SCHEMA: Final = "CP_VERITY_RULES_SCHEMA"
CP_TCB_IDENTITY_SCHEMA: Final = "CP_TCB_IDENTITY_SCHEMA"
CP_EXECUTION_PROVENANCE: Final = "CP_EXECUTION_PROVENANCE"
CP_PROVENANCE_BINDING: Final = "CP_PROVENANCE_BINDING"
CP_PROVENANCE_STATUS: Final = "CP_PROVENANCE_STATUS"
CP_PROVENANCE_AUTHORITY: Final = "CP_PROVENANCE_AUTHORITY"
CP_PROVENANCE_INPUT_SIZE: Final = "CP_PROVENANCE_INPUT_SIZE"
CP_PROVENANCE_INPUT_READ: Final = "CP_PROVENANCE_INPUT_READ"
CP_PROVENANCE_INPUT_CHANGED: Final = "CP_PROVENANCE_INPUT_CHANGED"
CP_PROVENANCE_ORACLE_DIGEST: Final = "CP_PROVENANCE_ORACLE_DIGEST"
CP_PROVENANCE_ORACLE_LOAD: Final = "CP_PROVENANCE_ORACLE_LOAD"
CP_PROVENANCE_ORACLE_INTERNAL: Final = "CP_PROVENANCE_ORACLE_INTERNAL"
CP_PROVENANCE_ARGUMENTS: Final = "CP_PROVENANCE_ARGUMENTS"
CP_PROVENANCE_V2_IMAGE_GEOMETRY: Final = "CP_PROVENANCE_V2_IMAGE_GEOMETRY"
CP_PROVENANCE_V2_MANIFEST_PRODUCTION: Final = "CP_PROVENANCE_V2_MANIFEST_PRODUCTION"
CP_PROVENANCE_V2_MANIFEST_SELFCHECK: Final = "CP_PROVENANCE_V2_MANIFEST_SELFCHECK"
CP_PROVENANCE_V2_SPDX_PRODUCTION: Final = "CP_PROVENANCE_V2_SPDX_PRODUCTION"
CP_PROVENANCE_V2_SPDX_SELFCHECK: Final = "CP_PROVENANCE_V2_SPDX_SELFCHECK"
CP_PROVENANCE_V2_MANIFEST_FORBIDDEN_FIELD: Final = "CP_PROVENANCE_V2_MANIFEST_FORBIDDEN_FIELD"
CP_TOOL_PIN_UNAVAILABLE: Final = "CP_TOOL_PIN_UNAVAILABLE"
CP_TOOL_PIN_CHANGED: Final = "CP_TOOL_PIN_CHANGED"
CP_PROVENANCE_V2_STAGING: Final = "CP_PROVENANCE_V2_STAGING"
CP_PROVENANCE_V2_LEASE: Final = "CP_PROVENANCE_V2_LEASE"
CP_PROVENANCE_V2_SCAVENGE: Final = "CP_PROVENANCE_V2_SCAVENGE"
CP_PROVENANCE_V2_BUNDLE_SHAPE: Final = "CP_PROVENANCE_V2_BUNDLE_SHAPE"
CP_PROVENANCE_V2_LOCAL_GATE: Final = "CP_PROVENANCE_V2_LOCAL_GATE"
CP_PROVENANCE_V2_BUNDLE_READONLY: Final = "CP_PROVENANCE_V2_BUNDLE_READONLY"
CP_PROVENANCE_V2_SAME_ADDRESS_DISAGREEMENT: Final = "CP_PROVENANCE_V2_SAME_ADDRESS_DISAGREEMENT"
CP_PROVENANCE_V2_RENAME: Final = "CP_PROVENANCE_V2_RENAME"

CP_MODULE_MISSING: Final = "CP_MODULE_MISSING"
CP_MODULE_COMPRESSED_UNSUPPORTED: Final = "CP_MODULE_COMPRESSED_UNSUPPORTED"
CP_MODULE_TRAILER: Final = "CP_MODULE_TRAILER"
CP_MODULE_CMS_VERIFY: Final = "CP_MODULE_CMS_VERIFY"
CP_MODULE_SIGNER: Final = "CP_MODULE_SIGNER"
CP_MODULE_KEYRING: Final = "CP_MODULE_KEYRING"
CP_FIRMWARE_INVENTORY: Final = "CP_FIRMWARE_INVENTORY"

CP_PROMOTE_STAGING: Final = "CP_PROMOTE_STAGING"
CP_PROMOTE_INSPECTION: Final = "CP_PROMOTE_INSPECTION"
CP_PROMOTE_SAME_LOCK_CONTENT_DISAGREEMENT: Final = "CP_PROMOTE_SAME_LOCK_CONTENT_DISAGREEMENT"
CP_PROMOTE_CONFLICT: Final = "CP_PROMOTE_CONFLICT"
CP_PROMOTE_RENAME: Final = "CP_PROMOTE_RENAME"
CP_PROMOTE_INTERRUPTED: Final = "CP_PROMOTE_INTERRUPTED"
CP_PROMOTE_NOT_PROMOTED: Final = "CP_PROMOTE_NOT_PROMOTED"


ALL_REASON_CODES: Final = frozenset(
    {
        CP_TOOL_MISSING,
        CP_TOOL_PATH_ESCAPE,
        CP_TOOL_DIGEST_MISMATCH,
        CP_TOOL_INVOCATION_FAILED,
        CP_HERMETIC_UNLISTED_READ,
        CP_HERMETIC_UNLISTED_WRITE,
        CP_HERMETIC_UNLISTED_SUBPROCESS,
        CP_HERMETIC_ENV,
        CP_HERMETIC_CLOCK,
        CP_HERMETIC_PATH_ESCAPE,
        CP_HERMETIC_NETWORK,
        CP_JSON_INVALID_UTF8,
        CP_JSON_INVALID,
        CP_JSON_NONCANONICAL,
        CP_JSON_DUPLICATE_KEY,
        CP_JSON_UNSUPPORTED_NUMBER,
        CP_JSON_UNSUPPORTED_TYPE,
        CP_LOCK_SCHEMA,
        CP_LOCK_DUPLICATE_ID,
        CP_LOCK_ROLE,
        CP_LOCK_INPUT_MISSING,
        CP_LOCK_INPUT_PATH_ESCAPE,
        CP_LOCK_DIGEST_MISMATCH,
        CP_LOCK_SIZE_MISMATCH,
        CP_LOCK_PROVENANCE,
        CP_LOCK_BASE_IMAGE_RECORD,
        CP_POLICY_SCHEMA,
        CP_POLICY_DUPLICATE,
        CP_POLICY_TREE_RULE,
        CP_POLICY_UNSUPPORTED_ACTIVATION,
        CP_POLICY_GRAPH_MISMATCH,
        CP_POLICY_FORBIDDEN_NETWORK,
        CP_POLICY_CAPABILITY,
        CP_TREE_MISSING,
        CP_TREE_UNEXPECTED,
        CP_TREE_NODE_TYPE,
        CP_TREE_METADATA,
        CP_TREE_XATTR,
        CP_TREE_ACL,
        CP_TREE_SYMLINK,
        CP_TREE_UNSUPPORTED_NODE,
        CP_TREE_SOURCE_BINDING,
        CP_SQUASHFS_BUILD,
        CP_SQUASHFS_EXTRACT,
        CP_VERITY_FORMAT,
        CP_VERITY_VERIFY,
        CP_VERITY_GEOMETRY,
        CP_VERITY_ROOT_MISMATCH,
        CP_IMAGE_DIGEST_MISMATCH,
        CP_MANIFEST_SCHEMA,
        CP_MANIFEST_FORBIDDEN_FIELD,
        CP_MANIFEST_DIFF,
        CP_SBOM_SCHEMA,
        CP_SBOM_DIFF,
        CP_SBOM_MAPPING,
        CP_RUNTIME_CLOSURE_SCHEMA,
        CP_VERITY_RULES_SCHEMA,
        CP_TCB_IDENTITY_SCHEMA,
        CP_EXECUTION_PROVENANCE,
        CP_PROVENANCE_BINDING,
        CP_PROVENANCE_STATUS,
        CP_PROVENANCE_AUTHORITY,
        CP_PROVENANCE_INPUT_SIZE,
        CP_PROVENANCE_INPUT_READ,
        CP_PROVENANCE_INPUT_CHANGED,
        CP_PROVENANCE_ORACLE_DIGEST,
        CP_PROVENANCE_ORACLE_LOAD,
        CP_PROVENANCE_ORACLE_INTERNAL,
        CP_PROVENANCE_ARGUMENTS,
        CP_PROVENANCE_V2_IMAGE_GEOMETRY,
        CP_PROVENANCE_V2_MANIFEST_PRODUCTION,
        CP_PROVENANCE_V2_MANIFEST_SELFCHECK,
        CP_PROVENANCE_V2_SPDX_PRODUCTION,
        CP_PROVENANCE_V2_SPDX_SELFCHECK,
        CP_PROVENANCE_V2_MANIFEST_FORBIDDEN_FIELD,
        CP_TOOL_PIN_UNAVAILABLE,
        CP_TOOL_PIN_CHANGED,
        CP_PROVENANCE_V2_STAGING,
        CP_PROVENANCE_V2_LEASE,
        CP_PROVENANCE_V2_SCAVENGE,
        CP_PROVENANCE_V2_BUNDLE_SHAPE,
        CP_PROVENANCE_V2_LOCAL_GATE,
        CP_PROVENANCE_V2_BUNDLE_READONLY,
        CP_PROVENANCE_V2_SAME_ADDRESS_DISAGREEMENT,
        CP_PROVENANCE_V2_RENAME,
        CP_MODULE_MISSING,
        CP_MODULE_COMPRESSED_UNSUPPORTED,
        CP_MODULE_TRAILER,
        CP_MODULE_CMS_VERIFY,
        CP_MODULE_SIGNER,
        CP_MODULE_KEYRING,
        CP_FIRMWARE_INVENTORY,
        CP_PROMOTE_STAGING,
        CP_PROMOTE_INSPECTION,
        CP_PROMOTE_SAME_LOCK_CONTENT_DISAGREEMENT,
        CP_PROMOTE_CONFLICT,
        CP_PROMOTE_RENAME,
        CP_PROMOTE_INTERRUPTED,
        CP_PROMOTE_NOT_PROMOTED,
    }
)


class ApplianceError(RuntimeError):
    """A conf-proc failure with a stable machine-readable reason code."""

    def __init__(self, reason_code: str, message: str) -> None:
        if reason_code not in ALL_REASON_CODES:
            raise ValueError(f"unknown conf-proc reason code: {reason_code!r}")
        self.reason_code = reason_code
        super().__init__(f"{reason_code}: {message}")
