#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Closed literal inventories for the SPP boot authority v3."""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum
from typing import Final

from conf_proc_spp_boot import BOOTSTRAP_MOUNTS_V2


# BOOTSTRAP_MOUNTS_V2 is public and remains the v3 bootstrap mount authority
# so the shared properties cannot silently drift.
BOOTSTRAP_MOUNTS_V3: Final = BOOTSTRAP_MOUNTS_V2

EARLY_MODULE_TARGET_KERNEL_RELEASE_V3: Final = "6.8.0-1058-azure-fde"
EARLY_MODULE_TARGET_CONFIG_SHA256_V3: Final = (
    "1ce93dd4569a7607db57f2b3321d38d0e0122fe29efa430374c3717ccbde68b9"
)
EARLY_MODULE_SIGNER_V3: Final = "Build time autogenerated kernel key"
EARLY_MODULE_SIGNATURE_KEY_ID_V3: Final = (
    "4C:F4:E0:34:2A:28:95:F1:5C:29:6C:20:CC:25:FC:B8:61:8D:B5:24"
)
EARLY_MODULE_RELEASE_ROOT_V3: Final = "/lib/modules/6.8.0-1058-azure-fde/"


@dataclass(frozen=True)
class EarlyModuleRowV3:
    path: str
    sha256: str


EARLY_MODULE_ROWS_V3: Final = (
    EarlyModuleRowV3(
        "kernel/drivers/md/dm-bufio.ko",
        "318df552f245da0e3bce5c047443f349d3771f044bfd9573ebe486a9056d107c",
    ),
    EarlyModuleRowV3(
        "kernel/drivers/md/dm-verity.ko",
        "31f7c5f1832ed81d4fa9290396d559b6e82d68eadb2df8b157fb71968431b6dc",
    ),
    EarlyModuleRowV3(
        "kernel/lib/libcrc32c.ko",
        "de152f89a11624f60b5c2ab74ff2bda86a1a8ecc7d110b37147e61abd5ab3c63",
    ),
    EarlyModuleRowV3(
        "kernel/net/netfilter/nfnetlink.ko",
        "b5eea11e088608fd57efaa8baf6059df9d4b0182df091bd2af7f686530cc69d3",
    ),
    EarlyModuleRowV3(
        "kernel/net/netfilter/nf_tables.ko",
        "2ea6941010d02f6c548fc259be178289a47698859ac9e6bcbbb30426bfd16589",
    ),
)
EARLY_MODULE_BUILTIN_DEPENDENCIES_V3: Final = (
    "crc32c_intel",
    "crc32c_generic",
)


@dataclass(frozen=True)
class KernelConfigBindingRowV3:
    symbol: str
    expected_value: str


KERNEL_CONFIG_BINDING_ROWS_V3: Final = (
    KernelConfigBindingRowV3("CONFIG_DEVTMPFS", "y"),
    KernelConfigBindingRowV3("CONFIG_BLK_DEV_NVME", "y"),
    KernelConfigBindingRowV3("CONFIG_BLK_DEV_DM", "y"),
    KernelConfigBindingRowV3("CONFIG_SQUASHFS", "y"),
    KernelConfigBindingRowV3("CONFIG_TCG_TPM", "y"),
    KernelConfigBindingRowV3("CONFIG_TCG_CRB", "y"),
    KernelConfigBindingRowV3("CONFIG_NETFILTER", "y"),
    KernelConfigBindingRowV3("CONFIG_DM_VERITY", "m"),
    KernelConfigBindingRowV3("CONFIG_NF_TABLES", "m"),
)
# Moving a named m capability to y requires a different fully bound v3
# contract; this literal table is intentionally not a compatibility policy.


@dataclass(frozen=True)
class ControlValueRuleV3:
    path: str
    accepted_pre_values: tuple[int, ...] | None
    accepted_pre_range: tuple[int, int] | None
    accepted_post_values: tuple[int, ...] | None
    post_formula: str | None


@dataclass(frozen=True)
class ControlInventoryRowV3:
    name: str
    value_rules: tuple[ControlValueRuleV3, ...]
    paired_requirements: tuple[str, ...]
    stage1_only_requirements: tuple[str, ...]


CONTROL_INVENTORY_ROWS_V3: Final = (
    ControlInventoryRowV3(
        "modules",
        (ControlValueRuleV3(
            "/proc/sys/kernel/modules_disabled", (0,), None, (1,), None,
        ),),
        ("deny_module_load_afterward",),
        (),
    ),
    ControlInventoryRowV3(
        "kexec",
        (ControlValueRuleV3(
            "/proc/sys/kernel/kexec_load_disabled", None, None, (1,), None,
        ),),
        (
            "/sys/kernel/security/lockdown=integrity_or_confidentiality",
            "deny_kexec_load_afterward",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "sysrq",
        (ControlValueRuleV3(
            "/proc/sys/kernel/sysrq", None, (0, 511), (0,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "unprivileged_bpf",
        (ControlValueRuleV3(
            "/proc/sys/kernel/unprivileged_bpf_disabled", (0, 1, 2), None, (1,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "userfaultfd",
        (ControlValueRuleV3(
            "/proc/sys/vm/unprivileged_userfaultfd", (0, 1), None, (0,), None,
        ),),
        (),
        (),
    ),
    ControlInventoryRowV3(
        "kernel_debug",
        (
            ControlValueRuleV3("/proc/sys/kernel/kptr_restrict", (0, 1, 2), None, (2,), None),
            ControlValueRuleV3("/proc/sys/kernel/dmesg_restrict", (0, 1), None, (1,), None),
            ControlValueRuleV3(
                "/proc/sys/kernel/perf_event_paranoid", (-1, 0, 1, 2, 3, 4), None,
                (3, 4), "max(pre,3)",
            ),
            ControlValueRuleV3("/proc/sys/kernel/yama/ptrace_scope", (0, 1, 2, 3), None, (3,), None),
        ),
        ("debugfs_absent_after_handoff", "proc_kcore_inaccessible_to_serving_identities"),
        ("debugfs", "/proc/kcore"),
    ),
    ControlInventoryRowV3(
        "recovery_operator_ingress",
        (),
        (
            "cmdline_absent:init=",
            "cmdline_absent:rd.break",
            "cmdline_absent:systemd.unit=",
            "cmdline_absent:systemd.debug_shell",
            "cmdline_absent:rescue",
            "cmdline_absent:emergency",
            "cmdline_absent:recovery",
            "no_getty_or_serial_reader",
            "no_ssh",
            "no_azure_agent",
            "no_run_command_or_extension_agent",
            "no_cloud_init",
            "no_container_socket",
            "no_interactive_process_or_listener",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "writable_roots",
        (),
        (
            "root_and_model_mappings_read_only",
            "ordinary_tmpfs=nosuid,nodev,noexec",
            "at_most_one_declared_jit_tmpfs=nosuid,nodev",
            "no_other_writable_executable_disk_backed_or_bind_backed_mount",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "tpm_closure",
        (),
        (
            "one_measured_attestation_broker_retains_pinned_tpm_resource_manager_after_pcr15_extend",
            "attestation_broker_exposes_quote_and_pcr_read_only_on_root_owned_unix_socket",
            "pid1_gateway_collector_model_processes_have_no_tpm_fd_device_path_or_capability",
        ),
        (),
    ),
    ControlInventoryRowV3(
        "persistence",
        (),
        (
            "/proc/swaps_has_no_row",
            "kdump_absent",
            "coredumps_disabled",
            "content_bearing_persistent_journaling_absent",
            "no_writable_block_device_mounted",
            "writable_log_request_cache_roots_are_declared_reboot_ephemeral_tmpfs",
        ),
        (),
    ),
)


@dataclass(frozen=True)
class DevDirectoryRowV3:
    path: str
    mode: int
    uid: int
    gid: int


@dataclass(frozen=True)
class DevTreeRowV3:
    path: str
    kind: str
    major_kind: str
    major_or_registration_key: int | str
    minor: int
    mode: int
    uid: int | None
    gid: int | None
    identity_binding: str | None


DEV_TREE_DIRECTORY_ROWS_V3: Final = (
    DevDirectoryRowV3("/dev", 0o755, 0, 0),
    DevDirectoryRowV3("/dev/nvidia-caps", 0o755, 0, 0),
)
DEV_TREE_ROWS_V3: Final = (
    DevTreeRowV3("/dev/console", "char", "literal", 5, 1, 0o600, 0, 0, None),
    DevTreeRowV3("/dev/null", "char", "literal", 1, 3, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/zero", "char", "literal", 1, 5, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/full", "char", "literal", 1, 7, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/random", "char", "literal", 1, 8, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/urandom", "char", "literal", 1, 9, 0o666, 0, 0, None),
    DevTreeRowV3(
        "/dev/tpmrm0", "char", "registered", "tpm_rm", 65536, 0o660,
        None, None, "sealed_attestation_broker",
    ),
    DevTreeRowV3("/dev/nvidia0", "char", "registered", "nvidia_gpu", 0, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidiactl", "char", "registered", "nvidia_gpu", 255, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-uvm", "char", "registered", "nvidia_uvm", 0, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-uvm-tools", "char", "registered", "nvidia_uvm", 1, 0o666, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-caps/nvidia-cap1", "char", "registered", "nvidia_caps", 1, 0o400, 0, 0, None),
    DevTreeRowV3("/dev/nvidia-caps/nvidia-cap2", "char", "registered", "nvidia_caps", 2, 0o400, 0, 0, None),
)
DEV_TREE_FORBIDDEN_PATH_PATTERNS_V3: Final = (
    "/dev/tpm0",
    "/dev/mapper/control",
    "/dev/dm-*",
    "any_block_device",
    "/dev/tty*",
    "/dev/ptmx",
    "/dev/pts*",
    "/dev/kmsg",
    "memory_device",
    "/dev/dri/*",
    "undeclared_nvidia_node",
)
DEV_TREE_FORBIDDEN_NODE_KINDS_V3: Final = (
    "symlink",
    "regular_file",
    "socket",
    "fifo",
    "submount",
)


FAILURE_DIAGNOSTIC_TOKENS_V3: Final = (
    "authority",
    "binding",
    "pid1",
    "adapter",
    "root_transition",
    "runtime_authority",
    "serving_integrity",
)
FAILURE_LATE_CODES_V3: Final = ("network_close", "poweroff_returned")
FAILURE_STAGES_V3: Final = (
    "diagnostic",
    "close_serving_network",
    "poweroff_requested",
    "fail_stop",
)


@dataclass(frozen=True)
class LaunchRoleRowV3:
    role: str
    lifecycle: str
    network_policy: str
    endpoint: str | None
    listener_policy: str
    admission_policy: str
    restart_policy: str


LAUNCH_ROLE_ROWS_V3: Final = (
    LaunchRoleRowV3(
        "attestation-broker", "one_long_lived", "no_network", "root_owned_local_socket",
        "no_listener", "none", "never",
    ),
    LaunchRoleRowV3(
        "inference", "one_long_lived", "loopback_only", "127.0.0.1:8000",
        "one_loopback_listener", "none", "never",
    ),
    LaunchRoleRowV3(
        "asr", "one_long_lived", "loopback_only", "127.0.0.1:8100",
        "one_loopback_listener", "none", "never",
    ),
    LaunchRoleRowV3(
        "gateway", "one_long_lived", "ra_tls_only", None,
        "no_listening_socket", "pid1_admitted_connected_fds_only", "never",
    ),
    LaunchRoleRowV3(
        "collector", "zero_or_one_transient", "no_listener", None,
        "no_listener", "pid1_spawned_reaped_one_bounded_request_response", "never",
    ),
)


@dataclass(frozen=True)
class ResourceActionRowV3:
    ordinal: int
    name: str


RESOURCE_ACTION_ROWS_V3: Final = (
    ResourceActionRowV3(1, "session_acquire"),
    ResourceActionRowV3(2, "collector_acquire"),
    ResourceActionRowV3(3, "collector_finish"),
    ResourceActionRowV3(4, "collector_abort"),
    ResourceActionRowV3(5, "request_acquire"),
    ResourceActionRowV3(6, "work_begin"),
    ResourceActionRowV3(7, "work_finish"),
    ResourceActionRowV3(8, "request_release"),
    ResourceActionRowV3(9, "session_release"),
    ResourceActionRowV3(10, "global_revoke"),
)
LISTEN_BACKLOG_V3: Final = 8
SOMAXCONN_MINIMUM_V3: Final = 8
MAX_LIVE_SESSIONS_V3: Final = 4
COLLECTOR_OPERATION_PERMITS_V3: Final = 1
COLLECTOR_OPERATION_BOUND_SECONDS_V3: Final = 180
COLLECTOR_OUTPUT_CAPACITY_BYTES_V3: Final = 8388608
ROUTE_WORK_PERMITS_TOTAL_V3: Final = 2
STREAM_BUFFER_BYTES_V3: Final = 2097152
AGGREGATE_BUFFER_BYTES_V3: Final = 4194304
REQUEST_HEAD_CAPACITY_BYTES_V3: Final = 32768
RELAY_COPY_CHUNK_BYTES_V3: Final = 65536


class ServingWireMessageTypeV3(IntEnum):
    SESSION_FD = 1
    COLLECTOR_REQUEST = 2
    COLLECTOR_RESPONSE = 3
    COLLECTOR_ACK_VALID = 4
    COLLECTOR_ACK_INVALID = 5
    COLLECTOR_CANCEL = 6
    REQUEST_ACQUIRE = 7
    REQUEST_ADMIT = 8
    REQUEST_REJECT = 9
    WORK_BEGIN = 10
    WORK_BEGUN = 11
    WORK_FINISH = 12
    WORK_FINISHED = 13
    REQUEST_RELEASE = 14
    REQUEST_RELEASED = 15
    SESSION_RELEASE = 16
    SESSION_RELEASED = 17
    PRE_REQUEST_REJECTED = 18
    GLOBAL_FAULT = 19
    CHUNK_ACK = 20
    SESSION_FD_ACK = 21
    GATEWAY_READINESS_PROBE = 22
    GATEWAY_READINESS_RESULT = 23


WIRE_MESSAGE_TYPE_ROWS_V3: Final = tuple(
    (message_type.value, message_type.name)
    for message_type in ServingWireMessageTypeV3
)
