#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Stable public failures for SPP trace-semantic appraisal."""

from __future__ import annotations

from typing import Final


CP_SPP_TRACE_SEMANTICS_TYPE: Final = "CP_SPP_TRACE_SEMANTICS_TYPE"
CP_SPP_TRACE_SEMANTICS_CAP: Final = "CP_SPP_TRACE_SEMANTICS_CAP"
CP_SPP_TRACE_SEMANTICS_PLAN: Final = "CP_SPP_TRACE_SEMANTICS_PLAN"
CP_SPP_TRACE_SEMANTICS_HEADER: Final = "CP_SPP_TRACE_SEMANTICS_HEADER"
CP_SPP_TRACE_SEMANTICS_FRAME: Final = "CP_SPP_TRACE_SEMANTICS_FRAME"
CP_SPP_TRACE_SEMANTICS_SEQUENCE: Final = "CP_SPP_TRACE_SEMANTICS_SEQUENCE"
CP_SPP_TRACE_SEMANTICS_LIFECYCLE: Final = "CP_SPP_TRACE_SEMANTICS_LIFECYCLE"
CP_SPP_TRACE_SEMANTICS_TASK: Final = "CP_SPP_TRACE_SEMANTICS_TASK"
CP_SPP_TRACE_SEMANTICS_OPERATION: Final = "CP_SPP_TRACE_SEMANTICS_OPERATION"
CP_SPP_TRACE_SEMANTICS_PHASE: Final = "CP_SPP_TRACE_SEMANTICS_PHASE"
CP_SPP_TRACE_SEMANTICS_CONTROL: Final = "CP_SPP_TRACE_SEMANTICS_CONTROL"
CP_SPP_TRACE_SEMANTICS_RESULT: Final = "CP_SPP_TRACE_SEMANTICS_RESULT"
CP_SPP_TRACE_SEMANTICS_LEDGER: Final = "CP_SPP_TRACE_SEMANTICS_LEDGER"
CP_SPP_TRACE_SEMANTICS_PRIVACY: Final = "CP_SPP_TRACE_SEMANTICS_PRIVACY"

ALL_SPP_TRACE_SEMANTIC_REASONS: Final = frozenset(
    {
        CP_SPP_TRACE_SEMANTICS_TYPE,
        CP_SPP_TRACE_SEMANTICS_CAP,
        CP_SPP_TRACE_SEMANTICS_PLAN,
        CP_SPP_TRACE_SEMANTICS_HEADER,
        CP_SPP_TRACE_SEMANTICS_FRAME,
        CP_SPP_TRACE_SEMANTICS_SEQUENCE,
        CP_SPP_TRACE_SEMANTICS_LIFECYCLE,
        CP_SPP_TRACE_SEMANTICS_TASK,
        CP_SPP_TRACE_SEMANTICS_OPERATION,
        CP_SPP_TRACE_SEMANTICS_PHASE,
        CP_SPP_TRACE_SEMANTICS_CONTROL,
        CP_SPP_TRACE_SEMANTICS_RESULT,
        CP_SPP_TRACE_SEMANTICS_LEDGER,
        CP_SPP_TRACE_SEMANTICS_PRIVACY,
    }
)


class TraceSemanticsError(RuntimeError):
    """One stable reason and no caller-derived public message."""

    def __init__(self, reason_code: str) -> None:
        if reason_code not in ALL_SPP_TRACE_SEMANTIC_REASONS:
            raise ValueError("unknown SPP trace-semantic reason")
        self.reason_code = reason_code
        super().__init__(reason_code)
