#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2026 sol pbc
"""Stable reason codes and failure type for SPP boot authority v3."""

from __future__ import annotations

from typing import Final


CP_BOOT_V3_SCHEMA: Final = "CP_BOOT_V3_SCHEMA"
CP_BOOT_V3_BINDING: Final = "CP_BOOT_V3_BINDING"
CP_BOOT_V3_PCR: Final = "CP_BOOT_V3_PCR"
CP_BOOT_V3_LATCH: Final = "CP_BOOT_V3_LATCH"
CP_BOOT_V3_MODULE_AUTHORITY: Final = "CP_BOOT_V3_MODULE_AUTHORITY"
CP_BOOT_V3_NETWORK_POLICY: Final = "CP_BOOT_V3_NETWORK_POLICY"
CP_BOOT_V3_MOUNT_CENSUS: Final = "CP_BOOT_V3_MOUNT_CENSUS"
CP_BOOT_V3_ROOT_TRANSITION: Final = "CP_BOOT_V3_ROOT_TRANSITION"
CP_BOOT_V3_CONTROL: Final = "CP_BOOT_V3_CONTROL"
CP_BOOT_V3_DEV_TREE: Final = "CP_BOOT_V3_DEV_TREE"
CP_BOOT_V3_DEVICE_MONITOR: Final = "CP_BOOT_V3_DEVICE_MONITOR"
CP_BOOT_V3_LAUNCH_SUPERVISION: Final = "CP_BOOT_V3_LAUNCH_SUPERVISION"
CP_BOOT_V3_RESOURCE_REDUCER: Final = "CP_BOOT_V3_RESOURCE_REDUCER"
CP_BOOT_V3_WIRE_PROTOCOL: Final = "CP_BOOT_V3_WIRE_PROTOCOL"
CP_BOOT_V3_SERVING_SESSION: Final = "CP_BOOT_V3_SERVING_SESSION"
CP_BOOT_V3_TRANSPORT_EPOCH: Final = "CP_BOOT_V3_TRANSPORT_EPOCH"
CP_BOOT_V3_FAILURE_PROTOCOL: Final = "CP_BOOT_V3_FAILURE_PROTOCOL"
CP_BOOT_V3_PID1_IDENTITY: Final = "CP_BOOT_V3_PID1_IDENTITY"

CP_SPP_PAYLOAD_V3_AUTHORITY: Final = "CP_SPP_PAYLOAD_V3_AUTHORITY"
CP_SPP_PAYLOAD_V3_PLAN: Final = "CP_SPP_PAYLOAD_V3_PLAN"
CP_SPP_PAYLOAD_V3_SOURCE: Final = "CP_SPP_PAYLOAD_V3_SOURCE"
CP_SPP_PAYLOAD_V3_IMPORT: Final = "CP_SPP_PAYLOAD_V3_IMPORT"
CP_SPP_PAYLOAD_V3_ARCHIVE: Final = "CP_SPP_PAYLOAD_V3_ARCHIVE"
CP_SPP_PAYLOAD_V3_POLICY: Final = "CP_SPP_PAYLOAD_V3_POLICY"
CP_SPP_PAYLOAD_V3_CONSISTENCY: Final = "CP_SPP_PAYLOAD_V3_CONSISTENCY"
CP_SPP_PAYLOAD_V3_STAGING: Final = "CP_SPP_PAYLOAD_V3_STAGING"
CP_SPP_PAYLOAD_V3_ADDRESS: Final = "CP_SPP_PAYLOAD_V3_ADDRESS"


ALL_REASON_CODES_V3: Final = frozenset(
    {
        CP_BOOT_V3_SCHEMA,
        CP_BOOT_V3_BINDING,
        CP_BOOT_V3_PCR,
        CP_BOOT_V3_LATCH,
        CP_BOOT_V3_MODULE_AUTHORITY,
        CP_BOOT_V3_NETWORK_POLICY,
        CP_BOOT_V3_MOUNT_CENSUS,
        CP_BOOT_V3_ROOT_TRANSITION,
        CP_BOOT_V3_CONTROL,
        CP_BOOT_V3_DEV_TREE,
        CP_BOOT_V3_DEVICE_MONITOR,
        CP_BOOT_V3_LAUNCH_SUPERVISION,
        CP_BOOT_V3_RESOURCE_REDUCER,
        CP_BOOT_V3_WIRE_PROTOCOL,
        CP_BOOT_V3_SERVING_SESSION,
        CP_BOOT_V3_TRANSPORT_EPOCH,
        CP_BOOT_V3_FAILURE_PROTOCOL,
        CP_BOOT_V3_PID1_IDENTITY,
        CP_SPP_PAYLOAD_V3_AUTHORITY,
        CP_SPP_PAYLOAD_V3_PLAN,
        CP_SPP_PAYLOAD_V3_SOURCE,
        CP_SPP_PAYLOAD_V3_IMPORT,
        CP_SPP_PAYLOAD_V3_ARCHIVE,
        CP_SPP_PAYLOAD_V3_POLICY,
        CP_SPP_PAYLOAD_V3_CONSISTENCY,
        CP_SPP_PAYLOAD_V3_STAGING,
        CP_SPP_PAYLOAD_V3_ADDRESS,
    }
)


class ApplianceErrorV3(RuntimeError):
    """An SPP boot authority v3 failure with a stable reason code."""

    def __init__(self, reason_code: str, message: str) -> None:
        if reason_code not in ALL_REASON_CODES_V3:
            raise ValueError(f"unknown conf-proc v3 reason code: {reason_code!r}")
        self.reason_code = reason_code
        super().__init__(f"{reason_code}: {message}")
