/* SPDX-License-Identifier: GPL-2.0-only */
/* Mechanically generated from conf_proc_spp_diag_trace.h/.c. Do not edit. */

#ifndef SPP_DIAG_TRACE_CORE_PROTOCOL_CONSTANTS_H
#define SPP_DIAG_TRACE_CORE_PROTOCOL_CONSTANTS_H

#define WIRE_OK 0
#define WIRE_NULL 1
#define WIRE_BUFFER_TOO_SMALL 2
#define WIRE_MAGIC 3
#define WIRE_VERSION 4
#define WIRE_LENGTH 5
#define WIRE_VALUE 6
#define WIRE_RESERVED 7
#define WIRE_CAP 8
#define WIRE_ARITHMETIC 9
#define WIRE_EVENT 10
#define WIRE_FLAGS 11
#define WIRE_STATE 12
#define WIRE_SEQUENCE 13

#define SPP_DIAG_TRACE_HEADER_SIZE 192
#define SPP_DIAG_TRACE_PREIMAGE_SIZE 224
#define SPP_DIAG_TRACE_COMMAND_SIZE 128
#define SPP_DIAG_TRACE_IMA_SIZE 256
#define SPP_DIAG_TRACE_IMA_LABEL_LEN 18
#define SPP_DIAG_TRACE_SOURCE_COMMIT_LEN 20
#define SPP_DIAG_TRACE_WIRE_VERSION 1u
#define SPP_DIAG_TRACE_POLICY_VERSION 1u
#define SPP_DIAG_TRACE_POLICY_VERSION_PROVENANCE 2u
#define SPP_DIAG_TRACE_HASH_SHA256 1u
#define SPP_DIAG_TRACE_MAX_FRAMES 524288u
#define SPP_DIAG_TRACE_MAX_STREAM_BYTES 268435456ull
#define SPP_DIAG_TRACE_MAX_FRAME_BYTES 1088u
#define SPP_DIAG_TRACE_FRAME_HEADER_SIZE 44
#define SPP_DIAG_TRACE_STREAM_PREFIX_SIZE 4
#define SPP_DIAG_TRACE_STREAM_HEADER_ENTRY_SIZE 196
#define SPP_DIAG_TRACE_MAX_PATH_BYTES 1024
#define SPP_DIAG_TRACE_MAX_PAYLOAD_BYTES 1044
#define SPP_DIAG_TRACE_CHAIN_LEN 32
#define SPP_DIAG_TRACE_FRAME_PREIMAGE_DOMAIN_LEN 27
#define SPP_DIAG_TRACE_FRAME_PREIMAGE_MIN_SIZE 107
#define SPP_DIAG_TRACE_FRAME_PREIMAGE_MAX_SIZE 1151
#define SPP_DIAG_TRACE_HOOK_MASK 0xfull
#define SPP_DIAG_TRACE_HOOK_BPRM_CHECK_SECURITY (1ull << 0)
#define SPP_DIAG_TRACE_HOOK_BPRM_COMMITTED_CREDS (1ull << 1)
#define SPP_DIAG_TRACE_HOOK_TASK_ALLOC (1ull << 2)
#define SPP_DIAG_TRACE_HOOK_TASK_CREATED (1ull << 3)
#define SPP_DIAG_TRACE_HOOK_FILE_OPEN_ATTEMPT (1ull << 4)
#define SPP_DIAG_TRACE_HOOK_FILE_OPEN_POLICY (1ull << 5)
#define SPP_DIAG_TRACE_HOOK_MMAP_POLICY (1ull << 6)
#define SPP_DIAG_TRACE_HOOK_MPROTECT_POLICY (1ull << 7)
#define SPP_DIAG_TRACE_HOOK_CONNECT_POLICY (1ull << 8)
#define SPP_DIAG_TRACE_HOOK_SENDMSG_POLICY (1ull << 9)
#define SPP_DIAG_TRACE_HOOK_FILE_OPEN_RETURN (1ull << 10)
#define SPP_DIAG_TRACE_HOOK_MMAP_RETURN (1ull << 11)
#define SPP_DIAG_TRACE_HOOK_MPROTECT_RETURN (1ull << 12)
#define SPP_DIAG_TRACE_HOOK_CONNECT_RETURN (1ull << 13)
#define SPP_DIAG_TRACE_HOOK_SENDMSG_RETURN (1ull << 14)
#define SPP_DIAG_TRACE_HOOK_TASK_EXIT (1ull << 15)
#define SPP_DIAG_TRACE_HOOK_MASK_PROVENANCE 0xffffull
#define SPP_DIAG_TRACE_IMA_FRAME_COUNT_MIN 1ull
#define SPP_DIAG_TRACE_IMA_STREAM_BYTES_MIN 244ull
#define SPP_DIAG_TRACE_CMD_ADVANCE_PHASE 1u
#define SPP_DIAG_TRACE_CMD_SEAL 2u
#define SPP_DIAG_TRACE_CMD_ADVANCE_PHASE_MIN 2u
#define SPP_DIAG_TRACE_CMD_ADVANCE_PHASE_MAX 14u
#define SPP_DIAG_TRACE_CMD_SEAL_PHASE 15u
#define SPP_DIAG_TRACE_IMA_KIND_READY 1u
#define SPP_DIAG_TRACE_IMA_KIND_RELEASED 2u
#define SPP_DIAG_TRACE_IMA_KIND_SEALED 3u
#define SPP_DIAG_TRACE_IMA_STATE_LIST_READY 1u
#define SPP_DIAG_TRACE_IMA_STATE_LIST_RELEASED 2u
#define SPP_DIAG_TRACE_IMA_STATE_LIST_SEALED 3u
#define SPP_DIAG_TRACE_EVENT_CORE_INIT 1u
#define SPP_DIAG_TRACE_EVENT_PRE_RELEASE_EXEC_DENIED 2u
#define SPP_DIAG_TRACE_EVENT_IMA_READY 3u
#define SPP_DIAG_TRACE_EVENT_USERSPACE_RELEASE 4u
#define SPP_DIAG_TRACE_EVENT_EXEC_ATTEMPT 5u
#define SPP_DIAG_TRACE_EVENT_EXEC_COMMIT 6u
#define SPP_DIAG_TRACE_EVENT_TASK_ALLOC_ATTEMPT 7u
#define SPP_DIAG_TRACE_EVENT_TASK_CREATED 8u
#define SPP_DIAG_TRACE_EVENT_PHASE_MARKER 9u
#define SPP_DIAG_TRACE_EVENT_TERMINAL 10u
#define SPP_DIAG_TRACE_PHASE_PRE_RELEASE 0u
#define SPP_DIAG_TRACE_PHASE_INIT 1u
#define SPP_DIAG_TRACE_PHASE_COLD_START 2u
#define SPP_DIAG_TRACE_PHASE_SYNTHETIC_INFERENCE 3u
#define SPP_DIAG_TRACE_PHASE_POISON_IMPORT 4u
#define SPP_DIAG_TRACE_PHASE_POISON_MODULE 5u
#define SPP_DIAG_TRACE_PHASE_POISON_LIBRARY 6u
#define SPP_DIAG_TRACE_PHASE_REMOTE_PACKAGE 7u
#define SPP_DIAG_TRACE_PHASE_REMOTE_MODEL 8u
#define SPP_DIAG_TRACE_PHASE_REMOTE_PLUGIN 9u
#define SPP_DIAG_TRACE_PHASE_WRITABLE_EXEC 10u
#define SPP_DIAG_TRACE_PHASE_ATTACHED_DISK_EXEC 11u
#define SPP_DIAG_TRACE_PHASE_REMOTE_CODE 12u
#define SPP_DIAG_TRACE_PHASE_JIT_CACHE 13u
#define SPP_DIAG_TRACE_PHASE_EVIDENCE_FINALIZE 14u
#define SPP_DIAG_TRACE_PHASE_SEALED 15u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_FILE_OPEN_ATTEMPT 0x0100u
#define SPP_DIAG_TRACE_FILE_ACCESS_READ 1u
#define SPP_DIAG_TRACE_FILE_ACCESS_WRITE 2u
#define SPP_DIAG_TRACE_FILE_ACCESS_READ_WRITE 3u
#define SPP_DIAG_TRACE_FILE_ACCESS_PATH_ONLY 4u
#define SPP_DIAG_TRACE_FILE_MOD_CREATE 0x0001u
#define SPP_DIAG_TRACE_FILE_MOD_TRUNCATE 0x0002u
#define SPP_DIAG_TRACE_FILE_MOD_APPEND 0x0004u
#define SPP_DIAG_TRACE_FILE_MOD_NOFOLLOW 0x0008u
#define SPP_DIAG_TRACE_FILE_MOD_CLOEXEC 0x0010u
#define SPP_DIAG_TRACE_FILE_MOD_DIRECTORY 0x0020u
#define SPP_DIAG_TRACE_FILE_MOD_MASK 0x003fu
#define SPP_DIAG_TRACE_FILE_OPEN_ATTEMPT_PREFIX_SIZE 16u
#define SPP_DIAG_TRACE_FILE_OPEN_ATTEMPT_MIN_PAYLOAD 17u
#define SPP_DIAG_TRACE_FILE_OPEN_ATTEMPT_MAX_PAYLOAD 1040u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_FILE_POLICY_DECISION 0x0101u
#define SPP_DIAG_TRACE_POLICY_ALLOW 1u
#define SPP_DIAG_TRACE_POLICY_DENY 2u
#define SPP_DIAG_TRACE_FILE_OBJECT_REGULAR 1u
#define SPP_DIAG_TRACE_FILE_OBJECT_DIRECTORY 2u
#define SPP_DIAG_TRACE_FILE_OBJECT_MEMFD 3u
#define SPP_DIAG_TRACE_FILE_OBJECT_OTHER 4u
#define SPP_DIAG_TRACE_FILE_POLICY_DECISION_PAYLOAD_SIZE 48u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_EXEC_MAPPING_POLICY_DECISION 0x0102u
#define SPP_DIAG_TRACE_MAPPING_OPERATION_MMAP 1u
#define SPP_DIAG_TRACE_MAPPING_OPERATION_MPROTECT 2u
#define SPP_DIAG_TRACE_MAPPING_BACKING_ANONYMOUS 1u
#define SPP_DIAG_TRACE_MAPPING_BACKING_REGULAR 2u
#define SPP_DIAG_TRACE_MAPPING_BACKING_MEMFD 3u
#define SPP_DIAG_TRACE_MAPPING_BACKING_OTHER 4u
#define SPP_DIAG_TRACE_MAPPING_MODE_SHARED 1u
#define SPP_DIAG_TRACE_MAPPING_MODE_PRIVATE 2u
#define SPP_DIAG_TRACE_MAPPING_PROT_READ 0x00000001u
#define SPP_DIAG_TRACE_MAPPING_PROT_WRITE 0x00000002u
#define SPP_DIAG_TRACE_MAPPING_PROT_EXEC 0x00000004u
#define SPP_DIAG_TRACE_MAPPING_PROT_MASK 0x00000007u
#define SPP_DIAG_TRACE_EXEC_MAPPING_POLICY_DECISION_PAYLOAD_SIZE 64u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_NETWORK_POLICY_DECISION 0x0103u
#define SPP_DIAG_TRACE_NETWORK_OPERATION_CONNECT 1u
#define SPP_DIAG_TRACE_NETWORK_OPERATION_SENDMSG 2u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_IPV4 1u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_IPV6 2u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_UNSUPPORTED 3u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_MALFORMED 4u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_UNRESOLVED 5u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_SOURCE_EXPLICIT 1u
#define SPP_DIAG_TRACE_NETWORK_ENDPOINT_SOURCE_CONNECTED 2u
#define SPP_DIAG_TRACE_NETWORK_SOCKET_STREAM 1u
#define SPP_DIAG_TRACE_NETWORK_SOCKET_DGRAM 2u
#define SPP_DIAG_TRACE_NETWORK_SOCKET_RAW 3u
#define SPP_DIAG_TRACE_NETWORK_SOCKET_SEQPACKET 4u
#define SPP_DIAG_TRACE_NETWORK_SOCKET_OTHER 5u
#define SPP_DIAG_TRACE_NETWORK_FAMILY_AF_INET 2u
#define SPP_DIAG_TRACE_NETWORK_FAMILY_AF_INET6 10u
#define SPP_DIAG_TRACE_NETWORK_POLICY_DECISION_PAYLOAD_SIZE 64u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_OPERATION_RETURN 0x0104u
#define SPP_DIAG_TRACE_OPERATION_FILE_OPEN 1u
#define SPP_DIAG_TRACE_OPERATION_MMAP 2u
#define SPP_DIAG_TRACE_OPERATION_MPROTECT 3u
#define SPP_DIAG_TRACE_OPERATION_CONNECT 4u
#define SPP_DIAG_TRACE_OPERATION_SENDMSG 5u
#define SPP_DIAG_TRACE_OPERATION_EXEC 6u
#define SPP_DIAG_TRACE_OPERATION_RETURN_PAYLOAD_SIZE 16u
#define SPP_DIAG_TRACE_PROVENANCE_EVENT_TASK_EXIT 0x0105u
#define SPP_DIAG_TRACE_TASK_EXIT_PAYLOAD_SIZE 8u

#define SPP_DIAG_TRACE_SOURCE_COMMIT_BYTES \
	0x91, 0xa8, 0xe8, '&', 0x01, '/', 0xbb, 0x1c, 0x7f, 0x5c,\
	0xb2, 0xa3, '&', 0xc0, 0x8b, 0x13, 0xe3, 0x90, 0xf4, 'i'

#define SPP_DIAG_TRACE_MAGIC_HEADER_BYTES \
	'S', 'P', 'P', 'T', 'R', 'C', '1', 0x00

#define SPP_DIAG_TRACE_PREIMAGE_DOMAIN_BYTES \
	's', 'o', 'l', '-', 's', 'p', 'p', '-', 'd', 'i',\
	'a', 'g', '-', 't', 'r', 'a', 'c', 'e', '-', 'h',\
	'e', 'a', 'd', 'e', 'r', '/', 'v', '1'

#define SPP_DIAG_TRACE_FRAME_PREIMAGE_DOMAIN_BYTES \
	's', 'o', 'l', '-', 's', 'p', 'p', '-', 'd', 'i',\
	'a', 'g', '-', 't', 'r', 'a', 'c', 'e', '-', 'f',\
	'r', 'a', 'm', 'e', '/', 'v', '1'

#endif
